codeSprinterss/codeSprinterss

naarang/README.md, naarang/Tree/BOJ_1068.js, naarang/Tree/BOJ_11725.js, naarang/Tree/BOJ_14675.js, naarang/Tree/BOJ_6416.js, naarang/Tree/BOJ_9489.js
가장 막막하게 느껴졌던 문제였다..
고민되었던 2가지는 트리에 대한 정보를 어떻게 저장할 것인가랑 트리인지 확인을 어떻게 할 것인가였다!
1. 트리에 대한 정보 저장
- 우선 숫자 1차원 배열로 쭉 펼쳐버린 후에 트리의 간선 정보는 dictionary, 트리의 노드 정보는 Set 자료형을 이용해서 저장했다.
- 현재 노드로 들어오는 간선이 몇 개인지가 중요하기 때문에 tree = {}의 경우 key : 도착정점, value: 들어오는 정점 배열로 저장했다.
2. 트리인지 확인하기
- 문제에서 요구하는 트리의 조건은 다음과 같았다.
```
들어오는 간선이 하나도 없는 단 하나의 노드가 존재한다. 이를 루트(root) 노드라고 부른다.
루트 노드를 제외한 모든 노드는 반드시 단 하나의 들어오는 간선이 존재한다.
루트에서 다른 노드로 가는 경로는 반드시 가능하며, 유일하다. 이는 루트를 제외한 모든 노드에 성립해야 한다.
```
- 위의 조건을 검증하기 위해 루트노드가 1개인지와 들어오는 간선이 1개인지를 검사했다.
- 루트노드는 들어오는 간선이 1개도 없는 것이 루트 노드로 판단한다.
- 근데 루트에서 다른 노드로 가는 경로가 반드시 가능한지까지는 별도로 검사할 필요가 없었는데.. 이거는 그래프의 특성을 더 확인해봐야할 것 같다ㅠ
- 그리고 노드가 아무것도 없는 트리도 트리로 판단하는 것도 주의해야했다!
---
DFS 쓸까? BFS 쓸까? 한 depth 씩 내려가면서 해당 노드의 자식들을 한 번에 확인할 때는 BFS가 적합하다고 생각했다. 
DFS vs BFS도 다시 한 번 정리가 필요할듯ㅠ
이 문제에서 해당 …
=> [Tree] 1주차

hyeyeonismm/BruteForce/BOJ_1065.py, hyeyeonismm/BruteForce/BOJ_4673.py, hyeyeonismm/Greedy/BOJ_10610.py, hyeyeonismm/Greedy/BOJ_12904.py, hyeyeonismm/Greedy/BOJ_1543.py, hyeyeonismm/Sorting/BOJ_3273.py
__1065__
한큐에 풀었다!
__4673__
1+1(2) 2+2(4) 3+3(6) ... 11+1+1(13) 이런식으로 계속 등장하는 () 안의 수를 arr에 할당해주면 된다. arr은 결국 생성자가 모인 배열이 되기 때문에 arr의 값이 0인 것만 출력하면 구할 수 있다.
__1543__
중복으로 단어가 겹쳐서 나오는 경우를 제외하는 것이 관건이었다. 처음엔` for i in range(0,len(n),len(word))` 이런 식으로 for문으로 로직을 짰는데 맨 앞부터 일치하지 않는 경우, 겹치는 경우 제외하는 걸 못하겠어서 while문으로 바꿨더니 성공!
__12904__
처음에는 s->t의 로직을 짰는데 당연히 실패.. gpt한테 힌트만 달라했더니 t가 s가 되는 법으로 생각하라고 해서 사실상 메인 로직인 힌트를 얻고 풀었다.
__3273__
처음엔 투포인터로 풀 생각을 못하고 tmp 변수를 만들어서 x-arr[i]의 값을 저장하고, arr[i]이후의 값에 tmp가 있는 경우에는 count를 더해주는 방식으로 했었다. 
```python
n = int(input())
arr = list(map(int, input().split()))
x = int(input())
cnt = 0
for i in range(n):
tmp = x - arr[i]
if tmp in arr[i + 1 :]:
cnt += 1
print(cnt)
```
근데 시간초과 떠서 찾아보니 투포인터를 사용하는 것이었다.
이 후에도 left랑 right를 0으로 초기화하는 걸 빼먹어서 다시 짜야했음..
=> [BruteForce, Greedy, Sorting] 1주차

hyeyeonismm/Greedy/BOJ_13164.py, hyeyeonismm/Greedy/BOJ_13305.py, hyeyeonismm/Greedy/BOJ_1541.py, hyeyeonismm/Greedy/BOJ_20115.py
__1541__
* 최소값을 어케 구하지? => '-' 부호를 기준으로 나눠서 더함
* 어떻게 나누지? => split으로 나눔
* `['40+29']` 이런식으로 저장되는데 int로 어떻게 바꾸지? => +가 * 있다면 map함수를 통해 list로 저장하고, list의 원소를 모두 더해서 int 69로 바꿈
* 첫 번째 숫자는 항상 양수이기 때문에 summ변수를 n[0]으로 할당하고 for문을 통해 n[i] 값을 뺀다
__13305__
가격의 최소값을 구하는 문제
* dictionary로 해보려고 했는데 key 값이 중복이 안돼서 못쓴다는 걸 알았다
* 마지막 price 값은 사실상 필요가 없어서 삭제했음
* for문으로 순회돌다가 i가 i+1보다 작으면 i의 price값을 계속 가지고 있는다
__20115__
`drinks.remove(drinks[end])`를 했을 때는 시간초과로 오류가 떴는데 pop()함수로 바꾸니 정답이 됐다.
remove() 함수는 리스트에서 값을 찾아서 제거하는데, 이 과정이 O(n)의 시간이 걸림
pop() 함수는 특정 인덱스에서 요소를 제거하는데, 리스트의 끝에서 요소를 제거하는 경우에는 O(1)의 시간 복잡도가 걸림
__13164__
차이를 다 나열해서 가장 큰 값을 기준선으로 잡아서 나눈다.
기준선으로 나눈 값은 0으로 바꾸고 나머지 값들을 더한다.
=> 결국 sort함수를 사용해서 기준선을 제외한 나머지 값들을 sum하면 되는 문제였다
보석도둑 문제 그리디로 결국 못풀었는데 우선순위 큐를 함께 #사용해서 푸는거였다.. 다음주엔 우선순위 큐 공부하기..
=> [Greedy] 2주차

rlaalsghks8/src/dp/Problem1890.java, rlaalsghks8/src/greedy/Problem2839.java, rlaalsghks8/src/implement/Problem1292.java
1890번 
실버1 치고는 풀만 했음
2차원 배열에서 경계라인 조건을 생각해야함. 
탐색 방향이 오른쪽, 아래 두 가지라 간단함
```java
for(int i=0; i<n; i++){
for(int j=0; j<n; j++){
if(dp[i][j]==0 || board[i][j]==0)
continue;
int jump = board[i][j];
if(j+jump<n) //오른쪽 이동
dp[i][j+jump] += dp[i][j];
if(i+jump<n) //아래 이동
dp[i+jump][j] += dp[i][j];
}
}
``` 
jump는 2차원 배열에서 움직이는 칸 수를 dp에 더해서 결과 값을 dp값을 출력
1292번
배열을 생성하지 않고 index값으로 풀려하다가 실패함..
그냥 수열 만들고 풀어라~
2839번
greedy,dp문제고 보통 greedy형태는 큰 수부터 처리하고 작은 수를 마지막으로 처리하는 것이 좋음
=> [그리디,DP] 2주차

JungYujin/w1/미로찾기2178.java, JungYujin/w1/비밀번호찾기17219.java, JungYujin/w1/스택수열1874.java, JungYujin/w1/탑2493.java, JungYujin/w1/회사에있는사람7785.java, JungYujin/w2/단지번호붙이기2667.java, JungYujin/w2/수이어쓰기1748.java, JungYujin/w2/이장님초대9237.java, JungYujin/w2/일로만들기1463.java, JungYujin/w2/일이삼더하기9095.java
=> chore: 폴더 구조 변경

hyeyeonismm/Hash/BOJ_11478.py, hyeyeonismm/Hash/BOJ_1269.py, hyeyeonismm/Hash/BOJ_17219.py, hyeyeonismm/Hash/BOJ_1764.py, hyeyeonismm/Hash/BOJ_20291.py
1. 문자열 입력을 `sys.stdin.readline()` 을 통해 받아왔더니 개행문자까지 같이 받아와서 출력 결과가 다르게 발생했다.
`sys.stdin.readline().split()` 으로 받아오면 개행문자를 잘라낼 수 있다고 해서 해당 코드를 사용했다.
2. for문에서 확장자를 추가하고, 이를 정렬하고 count하는 코드로 짰더니 시간 초과가 나서 입력을 받을 때 확장자를 추가하고, 추가한 리스트에 확장자가 이미 있으면 +1을 하는 딕셔너리를 만들었다. 그리고 정렬해서 바로 출력했더니 시간초과가 나지 않았다.
=> [Hash] 3주차

rlaalsghks8/src/greedy/Problem1541.java, rlaalsghks8/src/greedy/Problem2217.java, rlaalsghks8/src/heap/Problem2075.java
2075번
어떤 방식으로 구현을 진행할지 고민을 많이함
처음에는 전체적인 정렬을 1차원 배열에 다 넣어서 내림차순으로 정렬 후
N*N-N번째로 출력하려고 했지만 런타임 에러 발생 
-> 이를 해결하기 위해 다른 풀이 참고 우선순위 큐를 사용하여 구현(자동으로 정렬이 되는 자료구조)
1541번
그리디 알고리즘 문제로 그리디 특성상 큰 수들을 처리하고 나머지 작은 수를 처리한다고 생각하면 될 것 같음. 따라서 +부분들을 먼저 처리하고 - 를 다음 처리하면 됨.
2217번
1541번을 풀고 다른 그리디 알고리즘도 푸는 느낌이 비슷한지 확인 
이 문제는 큰 수 찾기인데 큰수를 처리하는 것이 아닌 rope들을 내림차순으로 정렬을 하고 로프 개수를 곱해주면서 크기 비교를 하는 것, key word가 큰 수를 처리한다는 느낌이 들었음
solution
```java
for(int i=0; i<N; i++){
maxKg = Math.max(maxKg, ropeList[i]*(N-i));
}
```
=> [PQ,Greedy] 3주차

naarang/Math/BOJ_21920.js, naarang/Math/BOJ_2960.js, naarang/Math/BOJ_4134.js, naarang/Math/BOJ_5347.js, naarang/README.md, naarang/Tree/BOJ_3584.js
쉽게 최대공약수를 구하는 방법 -> 유클리드 호제법
`a와 b의 최대공배수 = (a * b) / a와 b의 최대공약수` 이므로 유클리드 호제법으로 최대공약수를 구하면 최대공배수고 쉽게 구할 수 있다
- a를 b로 나눈 나머지 r을 구하고
- b를 r로 나눈 나머지 r’을 구하고
- 다시 r을 r’로 나누는 과정을 반복해서 나머지가 0이 되었을 때 r’이 a와 b의 최대공약수이다.
```js
// 이때 a > b여야 함
function gcd(a, b){
while(b !== 0){
let r = a % b;
a = b;
b = r;
}
return a;
}
```
어떤 수 N의 약수는 항상 쌍으로 존재
→ 따라서 자연수 n이 √n보다 작은 소수들로 나눠떨어지지 않으면 자연수 n은 소수이다.
서로소는 두 수의 공약수가 1뿐이다 -> 따라서 최대공약수가 1이면 서로소
최대공약수는 유클리드 호제법으로 계산한다
문제에서 P도 지워야된다에 주의!
이 문제는 완전한 에라토스체네스의 해 알고리즘보다는 응용이어서 문제의 조건에 맞게 변형해야 했다!
가장 가까운 부모를 어떻게 찾을지에 대해 많이 고민했었다.
부모들의 경우를 쉽게 찾기 위해서 단방향으로 tree를 key - 자식, value - 부모 로 두고 탐색한다
첫번째 노드에서 부모 배열을 쭉 찾은 후에 두번째 노드도 타고 올라가면서 첫번째 부모 배열에서 같은 거 만나면 바로 답!으로 해결했다.
이때 Set 자료형으로 빠르게 탐색하고자 했다.
=> [Math, Tree] 3주차

JungYujin/Hash/숫자카드2_10816.java, JungYujin/Math/날짜계산1476.java, JungYujin/Math/소수구하기1929.java, JungYujin/Math/이름궁합테스트17269.java, JungYujin/Sorting/좌표정렬하기11650.java
11650 : 좌표정렬하기
Arrays.sort()를 사용하여 arr을 정렬
정렬 기준은 x 좌표를 우선으로 하고, x 좌표가 같을 경우 y 좌표를 기준으로 정렬
17269 : 이름궁합테스트
두 이름의 문자를 교차로 합치고, 남는 문자들을 뒤에 추가하여 name_list를 만든다.
각 문자를 미리 정의된 숫자(number 배열)로 변환하여 궁합을 계산한다.
인접한 숫자들의 합의 1의 자리를 반복적으로 구해 두 자리 숫자가 남을 때까지 계산한 뒤, 그 값을 백분율로 출력한다.
1476 : 날짜계산
주기 E (1 ≤ E ≤ 15), S (1 ≤ S ≤ 28), M (1 ≤ M ≤ 19)의 값을 입력받는다.
각 주기를 1씩 증가시키며 E, S, M이 입력받은 값과 같아지는 년도를 찾는다. 모든 주기를 주어진 최대값(15, 28, 19)을 넘으면 다시 1로 돌아가며 반복한다.
주어진 E, S, M에 맞는 년도를 출력한다.
1929 : 소수구하기
에라토스테네스의 체 알고리즘을 사용한다.
arr 배열을 만들어 초기 값을 1로 설정하고, 0과 1은 소수가 아니므로 0으로 설정한다.
2부터 시작하여 루트 n까지 각 수의 배수를 0으로 만들어 소수가 아닌 것을 걸러낸다.
m부터 n까지의 값 중 배열 값이 1인 숫자를 출력한다.
10816 : 숫자카드2
숫자 카드의 개수와 값을 입력받고, 이를 HashMap에 저장하여 각 숫자의 빈도수를 기록한다.
찾고자 하는 숫자 카드들이 주어지면, 각 숫자가 HashMap에 몇 번 등장하는지 확인한다.
StringBuilder를 사용하여 각 숫자의 개수를 공백으로 구분해 출력한다.
=> [Math, Hash, Sorting] 4주차

rlaalsghks8/src/dijkstra/Problem14889.java, rlaalsghks8/src/implement/Problem2108.java, rlaalsghks8/src/queue/Problem10845.java
14889번
이번 주차 어려운 문제로 팀을 나누고 나눈 값들을 계산해서 값을 계속 비교 dfs로 풀어도 되는 것 같음
2108번
쉬웠지만 최빈값 찾는 것이 어려웠음. 최빈값 찾는 건 처음에는 평균값으로 최빈값을 찾으려 했지만 아닌 경우도 있을 것 같아서 다른 풀이를 참고하여 구현을 함 다른 값들 출력은 조금만 생각하면 바로 나올 수 있음
```java
static int frequence(int[] list) {
int cnt[] = new int[8001];
int max = 0;
for(int i=0; i<list.length; i++) {
cnt[list[i]+4000]++;
max = Math.max(cnt[list[i]+4000], max);
}
ArrayList<Integer> max_idx = new ArrayList<>();
for(int i=0; i<=8000; i++)
if(max == cnt[i])
max_idx.add(i-4000);
return max_idx.size()>1? max_idx.get(1) : max_idx.get(0);
}
``` 
10845번 
큐를 구현하는 것으로 그냥 자료구조 한 번 복습해볼겸 구현해봄
FIFO(First- In First Out)
=> [bruteforce,Math,Queue] 5주차

JungYujin/DP/_2xn타일링11726.java, JungYujin/DP/_2xn타일링2_11727.java, JungYujin/DP/정수삼각형.java, JungYujin/Hash/베스트앨범.java, JungYujin/Hash/전화번호목록.java
프로그래머스 : 베스트앨범
어려웠어요.. 블로그를 참고해서 풀었음.
장르별로 총 플레이 수를 저장할 수 있는 해시맵과 장르 안에서 각 곡들의 인덱스와 플레이 수를 저장하는 해시맵을 선언
프로그래머스 : 전화번호목록
2중 for문으로 돌게 짜니까 효율성체크에서 통과 못 함. 그래서 for문을 한 번만 사용하도록 하기 위해 전화번호를 사전순으로 정렬.
그리고 뒤에 있는 번호가 앞에 있는 번호로 시작하는지 체크.
프로그래머스 : 정수삼각형
각 층의 원소에 대해 바로 위층의 가능한 값들 중 최댓값을 더해가며 누적
가장자리에 위치한 원소들은 비교할 값이 하나밖에 없기 때문에, 특별히 그 하나의 값만 더해주는 방식으로 처리
그 외의 원소는 두 개의 값 중 큰 값을 더함
마지막 층에서 최댓값을 찾아 반환
백준11726 : 2xn타일링
두가지로 나눌 수 있다.
1. n-1의 타일에 2x1세로 타일이 하나 붙어있거나
2. n-2 타일에 1x2 가로 타일이 두개 붙어 있거나.
그래서 점화식은 arr[i] = arr[i-1] + arr[i-2]
백준11727 : 2xn타일링2
2xn타일링과 같지만, 2번의 경우에서 가로로 두개 말고 사각형 하나를 놓을 수 있다는 점이 추가된다.
따라서 점화식을 arr[i] = arr[i-1] + 2 * arr[i-2]로 세울 수 있다.
=> [DP, Hash] 5주차

JungYujin/DP/쉬운계단수10844.java, JungYujin/DP/이동하기11048.java, JungYujin/DP/점프1890.java, JungYujin/Search/그림1926.java, JungYujin/Search/숨바꼭질1697.java
**쉬운계단수 : 10844**
한 자릿수는 전부 계단수로 계산된다.
j==0일때 다음 자릿수는 무조건 1이어야함.
j==9일때 다음 자릿수는 무조건 8이어야함.
그 외의 경우 다음 자릿수는 j-1 또는 j+1이어야 하므로, 그 두 가지 경우의 계단 수를 더함.
**이동하기 : 11048**
arr[i][j]는 위치 (i, j)까지 올 때 얻을 수 있는 최대 사탕의 개수이다.
각 칸에서는 왼쪽(arr[i][j-1]), 위쪽(arr[i-1][j]), 왼쪽 대각선 위(arr[i-1][j-1]) 중에서 가장 큰 값을 선택하고, 현재 칸의 사탕 개수를 더해 갱신함.
마지막 칸 arr[n][m]에 저장된 값을 출력함.
**점프 : 1890**
dp[i][j] 배열은 (i, j)까지 도달할 수 있는 경로의 개수를 저장한다.
각 칸 (i, j)에서, 해당 칸의 값(num = arr[i][j])만큼 오른쪽(dp[i][j+num]) 또는 아래쪽(dp[i+num][j])으로 이동할 수 있음.
이동할 수 있는 칸이 격자의 범위 안에 있을 경우, 해당 칸의 경로 개수에 현재 칸의 경로 개수를 더해줌.
**그림 : 1926**
bfs로 (a, b) 좌표에서 시작하여 상하좌우로 인접한 1들을 탐색하며 그림의 넓이(연결된 1들의 개수)를 계산함.
cnt는 그림의 갯수를 나타내고 max는 가장 큰 그림의 넓이를 나타냄.
**숨바꼭질 : 1697**
각 위치에서 한 칸 뒤로, 한 칸 앞으로, 점프로 갈 수 있는 곳들을 계산한다.
이전에 있었던 곳에서 +1한 수를 저장함.
배열의 범위를 벗어나는지 체크함
현재 있는 위치가 m(목적지)라면 …
=> [DP, Search] 6주차

naarang/Greedy/BOJ_19598.js, naarang/Greedy/BOJ_21758.js, naarang/README.md
모든 경우를 해볼 수는 없으니 케이스를 나누는 게 가장 중요했다!!
케이스는 크게 3가지로!
```
1. 꿀통 ~ 벌 ~ 벌 : 첫번째 벌 이동
2. 벌 ~ 꿀통 ~ 벌 : 꿀통 이동
3. 벌 ~ 벌 ~ 꿀통 : 두번째 벌 이동
```
그리고 시간 초과가 발생했는데 반복문으로 그때그때 구간의 합을 구하는 것보다 dp 하는 것처럼 모든 부분에서의 합을 구해놓고 조합해서 구간별로의 합을 구하는 것이 빨랐다!
---
시작과 종료시간을 각각 저장해서 시간 기준으로 정렬 -> 가장 많이 겹치는 시간대를 고르면 된다!
이때 시간이 같으면 시작 시간보다 종료시간이 먼저 오도록 정렬해야지 예외가 없었다!
지난번에 푼 강의실 배정 문제랑 똑같이 풀리는 거라서 복습하는 겸 쉽게 풀 수 있었다
---
=> [Greedy] 6주차

Goraniiii/Implementation/BOJ_14503.cpp, Goraniiii/Implementation/BOJ_16935.cpp, Goraniiii/Implementation/BOJ_16967.cpp, Goraniiii/Math/BOJ_17427.cpp, Goraniiii/Math/BOJ_4375.cpp
<b>BOJ_15990 배열돌리기</b>
단순히 배열을 뒤집거나 돌리거나 재배치하는 문제였으나, 행렬 계산의 가장 기초와 감을 잡아가는 문제였다. 이와 같은 문제를 더 많이 풀어봐야겠다
<b>BOJ_16967 : 배열 복원하기</b>
규칙과 문제에 제시된 식을 이용하면 어렵지 않았다. 다차원배열에서 인덱스를 잘 처리하는게 중요하다.
<b>BOJ_14503 : 로봇 청소기</b>
단순 시뮬레이션 문제로 주어진 문제 조건에 맞게 풀면 된다. 방향 처리를 direction 배열로 처리해서 보다 깔끔하게 하였다.
<b>BOJ_4375 : 1</b>
오랜만에 mod 함수의 특성에 대해 생각해보았다.
<b>BOJ_17427 : 약수의 합 2</b>
더 이상 이런 문제는 안 풀어도 될 것 같다..
오랜만에 공부하는 c++ 알고리즘인데 이제야 코드 감을 다시 찾은 것 같다..
=> [Implementation, Math] 6주차

Goraniiii/Brute Force/BOJ_14501.cpp, Goraniiii/Brute Force/BOJ_1759.cpp, Goraniiii/Brute Force/BOJ_3085.cpp, Goraniiii/Brute Force/BOJ_6064.cpp
<b>3085 : 사탕게임</b>
단순히 배열을 순회하면서 문제 조건에 맞는 케이스를 찾으면 된다.
새로운 배열을 만들어서 사탕 교환을 해결하려고 했는데, 1번의 교환만 이루어졌기때문에 그냥 다시 바꾸면 되는 문제였다.
<b>6064 : 카밍 달력</b>
처음에는 모든 경우의수를 모두 돌아보는 방법으로 하여서 타임아웃 발생.
숫자 케이스를 보자마자 최소공배수 문제인 것은 알았으나, 그 특성을 어떻게 적용할지에 대한 고민이 오래 걸렸다.
<b> 14501 : 퇴사</b>
브루트포스 + 점화식 문제
maxValue[k]를 k일부터 퇴사일까지 최대한의 이익이라고 생각하고 식을 짜면
maxValue[k] = max(maxValue[k + Tk] + Pk, maxValue[k + 1])
중복계산을 피하기위해서 maxValue 전체를 -1 로 초기화하고, 메모리제이션을 이용해 getMaxValue를 재귀호출했다.
<b>1759 : 암호 만들기</b>
주어진 문자열 ch 중 k번쨰부터 n개를 골라내 만들 수 있는 문자열의 집합을 S라 하자.
S(k, n)는 ch[k]로 시작하며, 뒤에 S(k + 1, n -1)의 원소들이 따라오는 형태의 집합과, S(k + 1, n) 집합의 합집합이다.
두 집합의 교집합은 없다.
=> [Brute Force] 7주차

hyeyeonismm/DFS_BFS/BOJ_10451.py, hyeyeonismm/DFS_BFS/BOJ_11724.py, hyeyeonismm/DFS_BFS/BOJ_2606.py, hyeyeonismm/Math_Implement/BOJ_17427.py, hyeyeonismm/Math_Implement/BOJ_1929.py, hyeyeonismm/Math_Implement/BOJ_2089.py
**2606**
전역 변수를 설정하는 global을 사용해보며 함수 외부에 정의된 변수를 수정해보았다.
**11724**
connection 한 바퀴 돌았을 때를 구하는 건 했는데 또다른 connection이 있는 경우 이걸 어떻게 할지…. 검색해봤는데 너무 쉬웠음.. 그냥 dfs 한 번 끝날 때마다 count+1을 해줌
다시 한 번 풀어봐야 될듯
**10451**
1. 인덱스를 맞추기 위해서 배열의 0번째 원소를 0으로 설정했어야 하는데 이게 좀 어려웠다. 근데 그냥 arr[1:]에 할당하면 됐었다..
2. 한 번의 사이클을 돌고 이후에 다른 사이클로 어떻게 넘어갈지가 어려웠다. for문을 통해서 visited가 false인 경우 다시 dfs함수가 돌도록 했다.
**2098**
n이 0인 경우 예외처리를 했어야 했다. exit() 함수를 통해 0을 출력하고 프로그램이 바로 종료되게 해야 한다. 처음에는 list로 받고, list를 reverse해서 print하는 방식으로 했는데, 문자열로 받아서 맨 앞글자에 추가하는 방식이 훨씬 간편했다.
**1929**
```
m, n = map(int, input().split())
arr = [1] * (n + 1)
arr[0] = arr[1] = 0
```
이 과정을 통해 arr을 초기화해줬다. 이제 소수 판별을 해서 소수가 아니면 arr을 0으로 바꾸고, 나중에 arr이 1인 것만 출력하는 알고리즘을 사용했다.
=> [DFS/BFS, Math] 7주차

naarang/DynamicProgramming/BOJ_11660.js, naarang/DynamicProgramming/BOJ_21317.js, naarang/Greedy/BOJ_8980.js, naarang/README.md
용량이 제한 되어 있으므로 특정장소에 도착했을 때 최대한 빨리 내리는 것 중에 최대한으로 가져오면 어떨까! 라고 처음에 새악ㄱ했는데
이게 아니라 상자가 내리는 시기가 빠른 순으로 전체 정렬한 다음에 박스를 실어야 할듯! 만약 도착 마을이 같으면 시작 마을이 빠른 순으로 정렬하기!
최대한 실고 갈 수 있는 만큼의 박스를 계산하는 것이 제일 어려웠다ㅠㅠㅠㅠ
---
일단 매우 큰 점프 고려 안하고 DP를 사용한 후에 가능한 모든 곳에서 매우 큰 점프 고려해서 다시 계산하기
최소값이 아닌 것 같더라도 끝까지 구해봐야된다 : new_dp[i] = Math.min(veryBigJump, new_dp[i])를 안해도 된다!
n === 1일때 예외처리 안해줘서 계속 찾았다ㅠㅠㅠ 다음부터는 예외처리를 꼼꼼히 하자!!
---
(0,0)을 기준으로 구간별 합 구하기
이후에 각 범위의 값 구하기 -> 이때 index 범위가 유효한지 확인 필수!
=> [Greedy/DP] 8주차

rlaalsghks8/src/dp/Problem2579.java, rlaalsghks8/src/search/Problem2178.java, rlaalsghks8/src/search/Problem2606.java
2606번
단지번호붙이기, 양배추 비슷문제와 유사하다 생각 dfs,bfs로 잡고 풀었다. 이건 1로부터 연결되어 있는 것을 찾아야 하므로 dfs가 맞다고 봄. 
2178번
최단거리 찾는 문제로 dfs보단 bfs가 맞다고 봤고 상하좌우 탐색을 해야함으로 nearX,nearY -> 이전에는 dx,dy로 풀긴했음, 2차원 배열 전체적 탐색이다 보니 x,y,값이 무조건 0보다 커야함. 보통 Queue를 사용해서 풀더라~
2579번
dp로 dp문제는 아직도 어렵고 감이 잘 안 잡힘. 점화식을 세워야하는데 규칙이나 이런 것을 찾기 어렵고 킥을 잡기 힘듬 이 문제의 킥은 포도주 문제와 다르게 2가지 경우만 생각하면 된다. 추가로 여기서 마지막 n번째 기준으로 경우가 2가지가 나옴 n-2에서 n을 가거나 n-3,n-2,n을 가거나 마지막 계단을 밟아야함으로 2가지 경우가 나옴 이걸 생각하는게.. 생각보다..ㅎㅎ
=> [Search/DP] 8주차

Goraniiii/Brute Force/BOJ_1182.cpp, Goraniiii/Implementation/BOJ_16931.cpp
=> [Implementation, BF] 9주차

rlaalsghks8/src/dp/Problem14501.java, rlaalsghks8/src/search/Problem2667.java
2667번 
dfs문제로 이전 유기농 양배추와 다른 유사 문제를 풀다가 다시 단지번호붙이기를 풀면 좋을 것 같아서 풀었음.
dfs 재귀로 푸는 것이 일반적으로 많이 풀며 미로찾기와 같이 한 루트에서 상하좌우 다 방문해야 할때는 dx[],dy[] 형태를 적용해서 
```java
public static void DFS(int x, int y) {
visit[x][y] = true;
regionCount++;
for (int i = 0; i < 4; i++) {
d_x = x + dirX[i];
d_y = y + dirY[i];
if (d_x >= 0 && d_x < N && d_y >= 0 && d_y < N) {
if (!visit[d_x][d_y] && square[d_x][d_y] == 1) {
DFS(d_x, d_y);
}
}
}
}
``` 
14501번 
dp문제 dfs로도 풀 수 있다고 함. 방식은 여러가지인데 뒤에서부터 일수를 줄여가면서 푸는 것도 가능하며
보통 dp문제는 dp배열을 따로 적용해서 푸는게 일반적이다.  dp의 값을 넣고 비교하여 크거나 작은 값을 출력함.
=> [DFS,DP] 10주차

Goraniiii/Graph/BOJ_11724.cpp, Goraniiii/Graph/BOJ_1260.cpp, Goraniiii/Graph/BOJ_7576.cpp
Graph 문제를 처음 풀어보았다
<b>BOJ_1260</b>
그래프 구현을 처음 해 보았다. 인접리스트와 인접행렬로 그래프를 구현할 수 있음을 복습했다.
<b>BOJ_11724</b>
연결 요소(Connected Component) 란? : 그래프에서 간선 연결에 따라 어느 한 지점에서 출발하였을 때 절대 도달할 수 없는 노드가 생길텐데, 서로 연결되어 있는 노드들의 집합을 연결 요소라고 한다.
<b>BOJ_7576</b>
최단경로찾기문제, BFS를 이용해서 풀었다.
=> [Graph] 10주차

rlaalsghks8/src/dp/Problem11053.java, rlaalsghks8/src/dp/Problem1904.java
11053번
계단오르기, 포도주 랑 유사 문제 DP문제로  
부분수열
dp[0] = {10}
dp[1] = {10,20}
dp[2] = {10}
dp[3] = {10,20,30}
dp[4] = {10,20}
dp[5] = {10,20,30,40}
Top-Down 방식으로 N번째 값에 대해 이전에 탐색한 결과물이 있는지 검사
없으면 dp[N]을 1로 초기화, 모든 부분수열의 길이는 1이상이라
N-1부터 0까지 노드 탐색하면서 N=4 -> 3~0까지 탐색하면서 작은  값들이 존재하는
경우 seq[2] = 10, seq[0]=10, i=2에서 재귀탐색하고 i=0에서 재귀탐색을 시작
i=2 dp[4], LIS(2)+1 재귀호출한 값중 큰 값을 dp[4]에 개인 여기서 +1은 이전 부분수열 N번째 원소가 추가 이러한 방식으로 동작
1904번
00,1로 이루어질 수 있는 경우의수를 체크하는 문제로 한 4,5,개 정도하다 보면
피보나치수열로 값이 증가하는 것을 확인할 수 있다 따라서 점화식 피보나치 수열식으로 
계산하면 값이 나옴 
an = an-1 + an-2
=> [DP] 11주차 

Goraniiii/Graph/BOJ_1707.cpp, Goraniiii/Graph/BOJ_2667.cpp, Goraniiii/Graph/BOJ_4963.cpp
<b>BOJ_2667 : 단지번호 붙이기</b>
2차원 평면상에서 탐색을 그래프 개념으로 이해하고 수행
문제 제목과 다르게 단지번호를 지정할 필요가 없으며, 마을 집을 확인하는 각 탐색의 노드수를 세면 되는 문제이다.
<b>BOJ_4963 : 섬의 개수</b>
BOJ_2667의 하위호환. 전체 섬을 확인하기 위해 탐색을 몇 회 반복해야하는지에 대한 문제
<b>BOJ_1707 : 이분 그래프</b>
처음에는 문제 이해하는데 어려움이 있었다. 
문제 이해 후 각 집합에 포함되는 노드 집합을 따로 저장하려고 했으나, 효율 문제로 기각
각 노드에 대해 어떤 집합에 속해야하는지를 마킹하고 인접노드끼리 각 집합에 속하는지를 확인했다.
<b>이번주 총평</b>
그래프 연습
=> [Graph] 11주차

hyeyeonismm/Math_Implement/PGS_12930.py, hyeyeonismm/Math_Implement/PGS_70129.py
**이진 변환 반복하기**
1. 0 제거하기
2. 문자열 개수구하기
3. 그 수를 이진법으로 바꾸기
4. 1이 될때까지 반복 
**이상한 문자 만들기**
반례 찾기 -> 공백이 문자열 사이에 있는 경우, 홀수에 대문자가 오는 경우
=> [Implementation] 12주차

Goraniiii/Brute Force/BOJ_16197.cpp, Goraniiii/Graph/BOJ_2178.cpp, Goraniiii/Graph/BOJ_7562.cpp
<b>BOJ_7562 : 나이트의 이동</b>
BFS를 이용해서 최소 경로를 탐색하는 문제였다. 최소 경로의 길이를 어떻게 저장할지 고민하였는데, 이전에 bfs를 공부하며 사용했던 visited 를 변형하여, 이전에 몇개의 노드를 방문하고 왔는지를 기록하였다.
<b>BOJ_2178 : 미로탐색 </b>
위의 문제와 거의 흡사한 문제였다. 어렵지 않게 풀이하였음
<b>BOJ_16197 : 두 동전</b>
문제의 일반적 케이스에 대한 해답을 도출하였으나, 백준 제출시 특정 테스트케이스에 대해 틀렸음을 발견. 아직 문제를 해결하지 못했으나, 기록용으로 이번주차에 커밋함. 두 동전의 상태를 기록하면서 BFS로 탐색을 수행하였고, 특정 상태(벽을 만남, 동전이 떨어짐, 동전이 겹쳐짐 등)에 대해 처리를 진행하였음.
<b>이번주 총평</b>
그래프와 탐색은 뗄 수 없는 관계임을 다시금 느꼈다. 특히 특정 조건에 대한 탐색은 각 state를 노드, 이동하게 되는 조건 혹은 액션을 엣지로 생각하여 풀게된다. 이전에 프언개와 형식언어 시간에 배운 개념을 활용하고 있다.
다음주에 16197의 구체적 상태 전이를 생각하고 다시 풀이하겠다.
=> [Graph, Brute Force] 12주차

naarang/README.md, naarang/TwoPointer/BOJ_11728.js, naarang/TwoPointer/BOJ_21921.js, naarang/TwoPointer/BOJ_2470.js
- 배열이나 리스트에서 두 개의 포인터를 사용해서 특정 조건을 만족하는 부분 구간을 효율적으로 탐색 하는 알고리즘
- 일반적으로 배열이나 리스트가 정렬되어 있을 때 사용
- O(N)에 빠르게 해결 가능
값의 크기가 커서 BigInt 써야 함
포인터가 양쪽 끝에서 시작되어야 함 -> 합의 값에 따라서 두 개의 포인터를 가운데로 이동시키고 pointer1 < pointer2 조건이 틀리면 종료한다!
let min = BigInt(2000000000); 처음에 1000000000로 설정해서 틀렸다! 두 수의 합이므로 최대는 2000000000이다!
=> [Two Pointer] 13주차

Goraniiii/Brute Force/BOJ_14225.cpp, Goraniiii/Brute Force/BOJ_16197.cpp, Goraniiii/Graph/BOJ_13023.cpp
<b>BOJ 16197 : 두 동전</b>
지난주에 시도했으나 해결하지 못한 문제로, 문제를 처음부터 다시 풀고 기존 코드와 비교하였다.
1. 문제를 다시 읽어보니 동전이 겹쳐질 가능성이 없으나 잘못 이해한 것을 발견
2. 이동횟수 검사 순서 문제
3. visited 조건 오류
지난주에는 다음과 같은 이유로 문제를 해결하지 못했음.
<b>BOJ 14225 : 부분수열의 합</b>
브루트포스 문제로 주어진 수열의 n개의 수에 대해 2^n 가지 시도를 하면 되는 문제였다.
모든 경우에 대해 마스킹을 하고 가장 작은 수를 찾음
<b>BOJ 13023</b>
주어진 그래프가 A->B->C->D->E 로 이어지는지 확인하는 문제인데, 방문한 노드를 다시 방문하지 않고 깊이 4인 그래프를 구성할 수 있는지 확인하는 탐색을 진행하였다.
=> [Brute Force, Graph] 13주차

naarang/README.md, naarang/TwoPointer/BOJ_15961.js, naarang/TwoPointer/BOJ_3151.js, naarang/TwoPointer/BOJ_7453.js
투 포인터를 이용하면 좋을 때
```
정렬된 배열에서 특정 조건을 만족하는 쌍, 경우를 찾는 것 -> 배열의 크기가 크므로 투 포인터를 이용하면 시간을 줄일 수 있다!
```
2명이 아니라 3명이면 어떻게 해야하는가...? -> 첫번째 사람을 고정한 상태에서 나머지 두 명을 찾아본다!
set에 index 3개를 저장하기 -> 메모리 초과 발생 -> 근데 생각해보니깐 중복이 발생하지 않아서 set이 필요가 없었다!
중복인 값들을 고려해야 함!
```
sum === 0 일 때 중복인 값을 해결하는 방법
1) students[pointer1] === students[pointer2]
두 개의 포인터 사이의 모든 값이 중복인 것이므로 해당 값의 개수들 중에서 2개를 
무작위로 선택하는 nC2의 경우의 수를 계산해야 함
그리고 더 이상 탐색할 필요가 없으므로 break;
2)  students[pointer1] !== students[pointer2]
첫번째 포인터와 중복된 값이 몇 개인지, 두번째 포인터와 중복된 값이 몇 개인지를 각각 구한 다음에 곱하면 경우의 수를 구할 수 있다!
그리고 투 포인터 값을 중복값만큼 갱신해주어야 함!
```
---
처음에 set으로 저장할까 했는데... -> 중복값들을 어떻게 처리하지?
- set이 아니라 Map으로 해서 key - 초밥 종류, value - 해당 종류의 개수로 해야겠다!
실행 시간이 오래 걸렸는데 다른 분들의 풀이를 찾아보니깐 map이 아니라 어차피 초밥의 가짓수가 d개 이므로 d만큼의 길이를 가진 배열을 만들어서 그곳에 초밥의 개수를 저장한 것 같다
--- …
=> [Two Pointer] 14주차

naarang/DynamicProgramming/BOJ_1520.js, naarang/DynamicProgramming/BOJ_2631.js, naarang/Implementation/BOJ_1244.js, naarang/Implementation/BOJ_2578.js, naarang/README.md
자리를 바꾸는 순서는 상관이 없다! 어떤 거를 바꿀지를 고르면 된다
이때 바꿀지 선택하지 않은 것들이 오름차순으로 정렬되어 있으면 된다
-> 그렇다면 학생들 중에서 이미 오름차순인 최대 부분 수열의 길이를 구하면 해당 길이가 바꾸지 않아도 되는 학생 수이다.
LIS 알고리즘(최장 증가 수열)을 이용해서 최대 부분 수열의 길이를 구하면 된다!
---
처음에 문제를 봤을 때 이게 DP가 아니라 그래프 탐색 같은데라는 생각이 들었다.
그냥 DFS로 상하좌우로 탐색을 하면 중복된 탐색이 많아져서 DP로 메모이제이션을 해서 DFS + DP로 풀어야 한다!
dp[x][y]는 (x, y)에서 목적지까지의 가능한 경로 수를 저장 + dfs에서 -1이 아니면 방문한 것으로 체크
이거는 나중에 다시 풀어봐야겠다ㅠ
---
이 문제는 쉽게 풀렸다!
20개씩 출력하는 코드를 더 깔끔하게 할 수 없을까 했는데 
slice를 이용해서 20개씩 슬라이싱 후 공백으로 연결 가능
```js
for (let i = 0; i < switches.length; i += 20) {
answer.push(switches.slice(i, i + 20).join(" ")); 
}
console.log(answer.join("\n"));
```
---
숫자가 불렸을 때 빙고 판에서 빠르게 찾기 위해서 dict를 사용해서 key - 숫자, value - 좌표값 을 저장
숫자가 불리면 true로 저장할 2차원 배열도 별도로 선언해서 빙고 개수를 검사함
어렵지는 않았지만 더 깔끔하게 푸는 방법들이 많다!
---
=> [DP/Implementation] 15주차

Goraniiii/Geomatric/BOJ_11758.cpp, Goraniiii/Geomatric/BOJ_2166.cpp, Goraniiii/Geomatric/BOJ_2170.cpp
<b>BOJ_11758 : CCW</b>
벡터 외적(cross product)을 이용해서 방향을 구했다
<b>BOJ_2166 : 다각형의 면적</b>
신발끈 공식을 이용해서 다각형의 면적을 구했다. 처음에는 하나의 꼭짓점을 기준으로 삼각형을 쪼개서 신발끈 공식을 적용하려고 했으나, 공식 자체가 꼭짓점이 주어진 모든 다각형에 대해 적용되는 것을 알게되었다.
신발끈공식 자체가 외적을 이용한 공식이다보니, 벡터 계산 관련하여 복습하게 되었다.
<b>BOJ_2170 : 선 긋기</b>
겹치는 선분에 대해서 처리하고 풀면 되는 문제였다. 문제는 어렵지 않았으나 시간조건이 빡빡했는데, o(N) 수준에서 끝나서 아이러니했다. 백준 15552번 내용을 참고하면 입출력 속도에 영향을 받은 것을 알 수 있다. 
ios_base::sync_with_stdio(false); // 입출력 속도 향상
cin.tie(NULL); // cin과 cout의 동기화 해제
위의 두 코드를 삽입하여 해결함.
=> [Geomatric] 1주차

rlaalsghks8/src/dijkstra/Problem1436.java, rlaalsghks8/src/dp/Problem1463.java, rlaalsghks8/src/dp/Problem2839.java
1463번
문제로 이번 문제는 생각해야하는 경우의 수가 많다. 
1. 6으로 나누어 떨어지는 수, -1까지
2. 3으로만 나누어지는 경우의 수와 -1
3. 2로만 나누어지는 경우의 수와 -1
4. 다 포함이 안되는 경우의 수는 -1 만 해준다.
-> 이렇게 조건을 걸어 놓고 재귀함수로 돌리면 된다.
그리고 항상 dp문제는 dp[] 배열을 생성하고 문제를 푸는게 약간의 디폴트인 것 같음
2893번 
가장 dp문제 중에서 생각하기 쉽고 풀기 쉬운 문제 만약 dp문제를 처음 접하게 되면 추천한다. 따로 배운 건 없고 약간 그리디 풀 듯이 푼 느낌?
1463번
런타임을 줄이려고 했는데 생각보다 빡세고 조건 설정할게 많다. 흠.. 예시 답이 다른 게 있는데 이해가 안감;; 일단 간단하게 666을 기본적으로 깔고 간다고 생각
초기값을 666으로 증가시키면서 string으로 변환 666이 포함되었는지 확인
그럼 count 증가 count가 입력한 N이랑 같아지면 종료 num 출력 이건.. 좀 비효율적일지도.. 다른 코드 있던데 그건 조건 설정이 좀 많긴 했음 다시 확인해봐야할듯
=> [DP,BruteForce]

naarang/GraphTraversal/BOJ_1260.js, naarang/Implementation/BOJ_10994.js, naarang/Implementation/BOJ_14719.js, naarang/Implementation/BOJ_1913.js, naarang/Implementation/BOJ_2615.js, naarang/README.md
별 찍기 규칙을 찾아보기
별 개수가 n개라면
박스 크기 :
- 한 변의 길이 : 1, 5, 9, 13 -> 1 + 4(n - 1) 개
점점 사각형으로 감싸는 패턴이므로 재귀적으로 접근하는 것을 생각하는 것이 중요했다!
n = 1일 때만 
```
*
```
그 이후부터는 다음처럼 감싸는 사각형이 그려진다.
```
*****
*   *
*   *
*   *
*****
```
---
2중 for문으로 각 원소가 시작점인 경우 4가지를 확인한다.
아래로 5개, 오른쪽 위로 대각선으로 5개, 오른쪽으로 5개, 오른쪽 아래 대각선으로 5개가 존재하는지 확인
딱 5개인 것을 검사해야하는데 방향을 한쪽만 검사하는게 아니라 양쪽을 검사해야 함!
---
기준을 어떻게 잡을까? 처음에는 높은 기둥들을 찾으려고 했는데 
그게 아니라 아랫칸 라인부터 하나의 가로줄씩 순회하면서 물이 고일수 있으면 추가하는 것으로 생각!
---
오랜만에 DFS, BFS를 복습했다
DFS - 스택이용
BFS - 큐 이용
이때 주의할 조건은 방문할 수 있는 정점이 여러 개인 경우에는 정점 번호가 작은 것을 먼저 방문하기 위해 정렬을 하는데
DFS의 경우 스택이므로 내림차순 정렬, BFS는 오름차순 정렬해야했다!
=> [Implementation/Graph Traversal] 1주차

rlaalsghks8/src/implement/Problem1929.java, rlaalsghks8/src/queue/Problem2164.java, rlaalsghks8/src/search/Problem1920.java, rlaalsghks8/src/stack/Problem10773.java, rlaalsghks8/src/stack/Problem9012.java
9012번
처음에는 열린 괄호랑 닫힌 괄호가 갯수가 같으면 VPS인줄 알았는데 아닌 경우가 있다. 풀이를 보니 쉽게 이해함..
가장먼저 열린 괄호를 넣고 만약 리스트에 닫힌 괄호가 있으면 열린괄호를 빼준다. 만약 마지막에 열린괄호가 stack에 남아있으면 NO, 닫힌괄호가 나와서 빼줘야하는데 stack이 empty이면 NO를 반환 그 외에는 Yes.
1929번
이번주차 좀 많이 고민한 문제 하나하나 구간에서 배열을 돌아가면서 소수판단하는 이상한 방법은 runtime error가 발생할 것 같아서 다른 방식이 있나 봤는데 [에라토스테네스의 체] 방식이 있음 
배열에 구간 내에 있는 true,false를 넣고 
//sqrt하는 이유는 만약 1~10이면 3^2~4^2 사이이므로 2,3의 배수만 지워주면 됨
true일 경우 소수 x, false일 경우 소수
1920번
가장 먼저한 생각으로는 입력한 배열을 정렬한 다음 확인배열값에 하나하나 있나 확인하려고 했는데 이 방식은 runtime이 길어질 거 같아서 다른 방식으로는 이진탐색이 있음 이진탐색이란? 숫자 up and down 게임을 생각하면 되는데 예측값에 1~100이 있으면 17을 맞추려면 50을 말하고 down이면 다시 25를 말한다 이렇게 구간을 줄여나가는 형식으로 탐색을 진행하여 탐색 횟수를 줄이는 방법을 사용한다. 
2164번
Queue 문제로 생각보다 간단하게 구현가능, Queue에 대해서 다시 찾아봐야할듯 순환큐 -> 요고
10773번
queue도 구현하는것에있어서 부족한거 같길래. stack 관련 문제도 풀어보자 생각해서 풀게 됨 간단함 0아닌 …
=> [Stack,Queue,Search..]2주차

naarang/GraphTraversal/BOJ_1325.js, naarang/GraphTraversal/BOJ_14940.js, naarang/GraphTraversal/BOJ_16918.js, naarang/README.md
BFS로 풀었는데 메모리 초과 발생...
DFS에서는 각 층별로 모든 자식 노드를 저장해야 할 필요가 없기 때문에 BFS에 비해 메모리 요구량이 훨씬 적다!!
---
고려하지 못했던 반례 
```
input:
2 2
0 0
0 2
output:
-1 0 
0 0 
answer:
0 0 
0 0
```
0과 -1을 어떻게 구분해서 처리해야할 지 고민했는데 일단 다 -1로 처리하고 실제로 0인 값은 나중에 -1 -> 0으로 반영하기
한번에 간단하게 처리하려고 생각해서 어려웠다ㅠ
---
이거는 그래프 탐색은 아닌 것 같다! 그냥 구현 문제같았음
언제 터져야하는지를 저장하자! -> 현재 초에서 3초후로! 2차원 배열에 저장
주의할 점은 폭탄 폭발 시에 동시에 터지게 만들어야 함! 따라서 좌표를 받아서 한번에 처리
=> [Graph Traversal] 2주차

hyeyeonismm/stack/BOJ_10773.py, hyeyeonismm/stack/BOJ_10828.py, hyeyeonismm/stack/BOJ_1874.py
`remove` 로 처음에 코드 짰는데 오답 처리됨
→ remove는 스택 안에 똑같은 숫자가 여러개 들어있으면 맨 위의 값이 아닌 중복된 다른 값을 지워버릴 수 있음 `list.remove(값)` 형식으로 쓰이기때문.. 따라서 `list.pop()` 을 써야한다.
=> [2주차] stack

JungYujin/Implementation/더하기사이클1110.java, JungYujin/Implementation/방번호1475.java
오랜만에 돌아왔습니다. 알고리즘을 어떻게 푸는 건지 아예 완전히 까먹었어요. 그래서 기초 문제를 풀었어요.
구현 문제를 풀고 다른 사람들의 코드도 보면서 느끼는 점은, 같은 코드를 짜더라도 너무 다양한 방법이 있다는 점이었습니다.
나는 세네 줄로 짰는데 누군 한 줄로 짰더라구요. 고민을 많이 해보겠습니다.
=> [Implementation] 2주차

SeungJi20/Stack/BOJ_10828.py, SeungJi20/Stack/BOJ_12605.py, SeungJi20/String/BOJ_11720.py
**10828 : 스택**
sys.stdin.readline()을 사용 -> 한 줄씩 입력을 받아 처리
**11720 : 숫자의 합**
```
numbers = list(map(int, input()))
print(sum(numbers))
```
for문을 사용해서 작성했는데, map과 sum을 이용하면 더 간단한 코드를 만들 수 있었다.
map(int, input())을 사용해 숫자 문자열 전체를 한 번에 정수 리스트로 변환할 수 있다.
**12605 : 단어순서 뒤집기**
* enumerate() 함수 : 반복문에서 인덱스와 값을 동시에 사용할 수 있도록 해주는 함수로, 코드에서 인덱스를 자동으로 증가시켜 반복할 때 유용하다.
* 리스트를 역순으로 만드는 방법
: reversed() 함수나 [::-1]을 사용한다.(리스트나 튜플에도 적용 가능)
예) S[4::-1] => 4번 인덱스부터 0번 인덱스까지 역순으로 출력
=> [Stack,String] 3주차

hyeyeonismm/queue/BOJ_10845.py, hyeyeonismm/queue/BOJ_2164.py, hyeyeonismm/stack/BOJ_1874.py
**1021번**
반복문을 돌며 큐[i]의 값이 2가 아니라면 count+1
큐[i]의 값이 2라면 pop
이 때, 양방향 큐이기 때문에 더 최소로 움직이는 방향으로 가야한다. 
=> 다시 풀어봐야 함
=> [Queue] 3주차

rlaalsghks8/src/dp/Problem2579_2.java, rlaalsghks8/src/search/Problem1654.java, rlaalsghks8/src/search/Problem2805.java
1654번
랜선 자르기는 이분 탐색에 대표적인 문제라고 생각이 드는데
left,right,mid 값을 두고 range 내에 적합한 값을 찾아가는 문제
예를 들어 Up Down 게임에서 출제자가 17을 1~100까지에 숫자에서 맞춰보라고 낸다면 50부터 맞춰가는 것이 적합하듯이 이분탐색도 이러한 방식으로 값을 찾아가는 문제이다. 가장 중요한 코드로 생각이 드는 것은
```java
long right = lines[K-1];
long left = 1;
long count,mid;
while(left<=right){
count = 0;
mid = (left+right)/2;
for(int i=0; i<K ; i++){
count +=lines[i]/mid;
}
if(count<N) //작으면 right를 mid로 땡기고
right = mid-1;
else    //크면 left를 mid로 땡긴다.
left = mid+1;
}
``` 
2805번
이분 탐색 문제를 다시 풀어보는 것이 좋을 것 같아서 한 문제 더 추가해서 풀어보았다 위에 문제랑 큰 틀은 비슷한데 while문에서 left가 right보다 커질 때 종료되며 이분탐색에서 크게 벗어나진 않았던 문제이다. 
2579번
계단 오르기 문제로 이전에 풀었던 문제를 다시 복습할 겸 풀었지만.. 이번에도 어떤 식으로 풀지는 감은 잡았지만 생각보다 구현하는 것과 점화식을 생각하는 것에서 어려움을 겪었다... 점화식은 아직도 어렵다... dp는 연습을 많이 해야함..
=> [Search,DP] 3주차 

rlaalsghks8/src/search/Problem1260.java, rlaalsghks8/src/search/Problem1697.java
DFS와 BFS문제는 기본적으로 어떠한 방식으로 DFS,BFS의 방식으로 풀어야하는지 익히는 문제로
DFS는 일반적으로 재귀를 사용하여 탐색을 진행하고
BFS는 Queue 혹은 LinkedList를 사용하여 구현을 한다.
```java
public static void dfs(int start) {
check[start] = true;
sb.append(start + " ");
for(int i = 0 ; i <= node ; i++) {
if(arr[start][i] == 1 && !check[i])
dfs(i);
}
}
public static void bfs(int start) {
q.add(start);
check[start] = true;
while(!q.isEmpty()) {
start = q.poll();
sb.append(start + " ");
for(int i = 1 ; i <= node ; i++) {
if(arr[start][i] == 1 && !check[i]) {
q.add(i);
check[i] = true;
}
}
}
}
``` 
1697번
무지성으로 식만보고 적용해서 구현하면 런타임에러가 발생한다. 힌트를 통해서 BFS로 구현
=> [Search] 4주차

Goraniiii/Dynamic Programming/BOJ_15989.cpp, Goraniiii/Graph/BOJ_1446.cpp
<b>BOJ_15989:  1, 2, 3 더하기 4</b>
처음에는 각 케이스마다 구하려고 했으나, 점화식을 세우고 n의 범위가 크지 않아 전체를 구해놓고 시작함
<b>BOJ_1446: 지름길</b>
다익스트라 알고리즘 문제
=> [DP, Graph] 5주차

naarang/Backtracking/BOJ_15651.js, naarang/Backtracking/BOJ_15663.js, naarang/README.md
1. 
```js
const set = new Set([1, 2, 3]);
const arr = Array.from(set);
```
2. 
```js
const arr = [...set]
```
=> [Backtracking] 5주차 

JungYujin/Math/소수_팰린드롬1747.java, JungYujin/Math/수복원하기2312.java, JungYujin/Sorting/두수의합3273.java
2312 : 수 복원하기
입력받은 숫자들을 소인수분해 한다.
소수면 출력하고 아니라면 소인수와 그 개수를 계산해서 출력한다.
해시맵에 소인수의 개수를 저장하고, 마지막에 정렬해서 출력한다.
3272 : 두 수의 합
입력받은 배열을 정렬한다.
배열의 첫 인덱스를 startPoint로 두고 마지막 인덱스를 endPoint로 둔다.
startPoint + endPoint > x 라면 endPoint를 한 칸 앞으로 이동한다.
startPoint + endPoint < x 라면 startPoint를 한 칸 뒤로 이동한다.
startPoint + endPoint = x 라면 startPoint를 한 칸 뒤로, endPoint를 한 칸 앞으로 이동한다. 그리고 count를 1 증가시킨다.
1747 : 소수&팰린드롬
isPrime은 소수인지 판단하는 함수.
isPalind는 팰린드롬인지 판단하는 함수.
팰린드롬을 판단할 때는 숫자를 문자열로 바꿔서 판단한다.
=> [Math, Sorting] 5주차

hyeyeonismm/dp/BOJ_1003.py, hyeyeonismm/greedy/BOJ_1026.py, hyeyeonismm/greedy/BOJ_2847.py, hyeyeonismm/queue/BOJ_1021.py
**1003**
재귀로 문제에 접근하면 시간초과가 남.. 보통은 쪼개진 값(재귀)을 메모해둔다. 메모는 코드에서 배열로써 구현함 memo[100] 이런식으로 배열을 사용한다는 것을 힌트로 얻음
0과 1의 개수를 구하는 문제여서 배열 ans를 [0의개수, 1의개수]로 생성함
n == 0 : fib(0)
n == 1 : fib(1)
n == 2 : fib(0) + fib(1)
n == 3: fib(0) + fib(1) + fib(1) ==⇒ (2+1)
이런식으로 진행되기 때문에 이전의 0과 1값을 저장해놔서 누적하여 사용하는 방식으로 구현했음
=> [DP, Greedy] 5주차

chungchae/DFS_BFS/BOJ_1012.cpp, chungchae/DFS_BFS/BOJ_1260.cpp, chungchae/DFS_BFS/BOJ_2178.cpp
지난주 DFS에 이어 BFS를 학습했다. FIFO, queue 자료구조를 사용해 풀이한다.
기본적인 DFS와 BFS를 사용해 풀이했다. 
알고리즘 수업시간에는 DFS로 풀었는데 이번에는 BFS로 풀이했다.
```
void BFS(int a, int b) {
deque<pair<int, int>> Q;
Q.push_back(make_pair(a, b));
while (!Q.empty()) {
int now_x, now_y;
now_x = Q.front().first;
now_y = Q.front().second;
Q.pop_front();
visited[a][b] = true;
for (int k = 0; k < 4; k++) {
int x = now_x + dx[k];
int y = now_y + dy[k];
if (x >= 0 && y >= 0 && x < N && y < M) {
if (G[x][y] != 0 && !visited[x][y]) {
visited[x][y] = true;
G[x][y] = G[now_x][now_y] + 1;
Q.push_back(make_pair(x, y));
}
}
}
}
}
```
간단하게 BFS 횟수를 출력하면 된다. 테스트 케이스를 여러 개 받아서 초기화를 꼼꼼하게 해줘야 한다.
=> [DFS, BFS] 5주차

SeungJi20/Bruteforcing/BOJ_1977.py, SeungJi20/Bruteforcing/BOJ_2231.py, SeungJi20/Bruteforcing/BOJ_2501.py
1977 : 완전제곱수
제곱수 표현 방법
`square = i ** 2 `
시작값부터 끝값까지 반복하면서, 그 숫자가 제곱수인지 확인하고 범위에 포함되면 합산한다.
2231 : 분해합
숫자를 자릿수로 분해하여 각 자릿수를 더한 값을 원래 숫자와 비교해서 푼다.
else 위치가 순간 헷갈렸는데,
if 문 아래에 바로 있게 되면 if문이 아닐 때마다 0을 출력하게 되기 때문에,
for문 자체가 끝나고 실행돼야 하기 때문에 for문 아래에 있어야 한다.
2501 : 약수 구하기
K번째를 찾을 때 arr[K-1]인 점을 주의해야 한다!
=> [BruteForce] 5주차

hyeyeonismm/implement/BOJ_1037.py
**1065**
처음에 이중for문으로 구현했는데 더 쉬운 방법이 있다는 것을 찾아보게 되었다. 언제나 최적화가 중요..
**1193**
분수찾기에 규칙이 있으니 더 찾아봐야 함
=> [Implement]

Goraniiii/Graph/BOJ_1389.cpp, Goraniiii/Graph/BOJ_16929.cpp, Goraniiii/Greedy/BOJ_1080.cpp
=> [Greedy, Graph] 6주차

rlaalsghks8/src/bruteforce/Problem3085.java, rlaalsghks8/src/dp/Problem1932.java, rlaalsghks8/src/search/Problem1926.java
코테 시험에 앞서서 가장 약한 DP를 먼저 공부하였습니다.
1932번
점화식을 생각해 내는게 어려움
```java
for(int i=1; i<n; i++) {
for(int j=0; j<=i; j++) {
if(j==0) {
dp[i][j]=dp[i-1][j]+arr[i][j];
}
else if(j==j+i) {
dp[i][j]=dp[i-1][j-1]+arr[i][j];
}
else {
dp[i][j]=Math.max(dp[i-1][j-1], dp[i-1][j])+arr[i][j];
}
}
}
``` 
3085번
모든 행과 열을 바꿔가면서 계산을 하는 것인가 의문이 들었는데 그게 맞다
알고리즘 분류에 브루트포스 알고리즘이므로 전체 열과 행을 바꾸며 최대값을 계산, 아닐 경우 다시 원상태로 복구
1926번
dp 다음으로 dfs,bfs 문제를 풀어보자 했음.. 아직도 어렵고 현대 오토에버에서 bfs가 나왔는데.. 좀 더 볼걸.. 후회중 이번주는 dp랑 bfs,dfs 좀 완벽히 해봐야겠다...
=> [Bruteforce,Seach] 6주차 

JungYujin/DP/상자넣기1965.java, JungYujin/Search/DFS와BFS1260.java
1260 : DFS와 BFS
DFS는 재귀를 사용한다. 간선이 존재하고 방문하지 않은 노드라면 다시 dfs를 진행한다. (더 깊이 내려간다)
BFS는 큐를 사용한다. 큐에 처음 삽입한 노드를 뽑아서 연결된 노드를 큐에 넣는다.
1965 : 상자넣기
가장 긴 증가하는 부분 수열(LIS)의 길이를 찾는 것.
dp[i]는 arr[i] 이전의 모든 요소 arr[j] (j < i) 중 작은 값을 찾아 최장 길이를 갱신한다.
최댓값을 갱신하며 순회한 후, 최종적으로 가장 긴 LIS 길이를 출력한다.
=> [DP/Serarch] 6주차

hyeyeonismm/implement/BOJ_1037.py
Reverts codeSprinterss/codeSprinterss#86
=> [Implement] 6주차

naarang/Backtracking/BOJ_2580.js, naarang/DivideAndConquer/BOJ_1030.js, naarang/DivideAndConquer/BOJ_1780.js, naarang/GraphTraversal/PGS_도넛과 막대 그래프.js, naarang/Implementation/PGS_가장많이받은선물.js, naarang/README.md
재귀 함수를 이용할 때 답을 찾은 다음에도 단순히 return만 했더니 계속 탐색이 진행되었다!
정답을 찾은 이후에 정답을 출력하고 불필요한 탐색은 없애는 부분을 신경써야함
---
실제 문제는 쪼개가지만 미리 각 칸들을 쪼갰다고 생각하고 접근함
메모리 초과 발생! -> 실제로 출력할 범위 이외의 부분은 탐색할 필요가 없었다!
따라서 모든 칸을 배열에 저장할 필요 없이 매개변수로 블랙인지 아닌지를 탐색할 isBlack을 추가해서 판단하는 것으로 변경했다!
---
이 문제는 처음에 dfs로 풀었는데 시간 초과가 발생!
사실 직접 모든 노드를 탐색할 필요 없이 해당 노드로 들어오는 간선의 수, 가리키는 간선의 수로 규칙을 찾아내는 것이 더 빨랐다
따라서 지금 풀이에서 개수를 더 깔끔하게 세도록 개선할 수 있을 것 같다!
=> [Backtracking/Divide and conquer] 6주차

chungchae/DFS_BFS/BOJ_1167.cpp, chungchae/binary_search/BOJ_1920.cpp, chungchae/greedy/BOJ_11047.cpp, chungchae/greedy/BOJ_1138.cpp, chungchae/greedy/BOJ_1715.cpp
이진 탐색과 그리디 알고리즘을 공부했다.
간단하게 이진 탐색을 사용해 시간 복잡도 조건을 맞춰 풀이했다.
```
while (start <= end) {
int midi = (start + end) / 2;
int midV = arr[midi];
if (midV > target) {
end = midi - 1;
}
else if (midV < target) {
start = midi + 1;
}
else {
find = true;
break; //escape while loop
}
}
```
그냥 vector로 풀이했다가, 시간 초과가 나서 우선순위 큐로 다시 풀었다.
memory 배열의 값을 인덱스로 설정하고, 기존 값이 존재하면 +1(반복) 하여 저장하는 식으로 구현했다가 반례 몇 개에 걸려서 알고리즘을 수정했다.
```
for (int i = 0; i < N; i++) {
int count = memory[i];
for (int j = 0; j < N; j++) {
if (answer[j] == 0) {
if (count == 0) {
answer[j] = i + 1;
break;
}
count--;
}
}
}
```
=> [binary search, greedy] 6주차

SeungJi20/String/BOJ_10808.py, SeungJi20/String/BOJ_14425.py, SeungJi20/String/BOJ_31403.py
10808 : 알파벳 개수
`print(c, end=" ")`
end=" "를 사용하여 각 출력 뒤에 공백을 추가하여, 결과를 수평으로 출력되게 하였다.
ord() 함수 : 문자를 아스키 코드 값으로 변환해주는 함수
14425 : 문자열 집합
이 문제는 list를 사용하면 시간 초과가 발생한다. (순차적으로 확인하기 때문)
set을 사용하여 풀면 set은 Hash Table을 이용하기 때문에 훨씬 빠르다.
* append : 리스트에 값 추가 , add : 집합에 중복없이 추가
31403 : A + B - C
=> [String] 6주차

chungchae/Data structure/BOJ_2075.cpp, chungchae/Math/BOJ_1614.cpp, chungchae/Math/BOJ_1747.cpp, chungchae/Math/BOJ_1929.cpp, chungchae/greedy/BOJ_1931.cpp
끝나는 시간 순으로 정렬한 뒤 greedy로 탐색한다.
일반적인 반복문으로 구했더니 시간이 초과되었다. 다친 손가락별로 switch 문을 작성해 풀이했다.
시간 제한을 고려해 우선순위 큐로 풀이했다.
에라토스테네스의 체 방식으로 풀이했다.
```
for (int i = 2; i <= sqrt(N); i++) {
if (arr[i]) {
for (int j = i + i; j <= N; j += i) {
if (j % i == 0) {
arr[j] = false;
}
}
}
}
```
위 문제와 유사하지만, 팰린드롬 조건을 한 번 더 검사해야 한다.
=> [greedy, math] 7주차

hyeyeonismm/dp/BOJ_9095.py, hyeyeonismm/sort/BOJ_1920.py, hyeyeonismm/stack/BOJ_9012.py
**9095**
점화식으로 풀었다. 파이썬에서 함수 만들 때 return문 사용에 대해 더 익숙해져야겠음
**1920**
이분탐색 공식 코드를 공부하고 풀었다
=> [DP, 정렬] 7주차

rlaalsghks8/src/greedy/Problem13305.java, rlaalsghks8/src/implement/Problem1735.java, rlaalsghks8/src/search/Problem1260.java, rlaalsghks8/src/sort/Problem3273.java
1260번
DFS,BFS 기본기 문제로 복습 차원으로 다시 문제를 풀어보았습니다.
미로문제 유형에서는 위,아래,오른쪽,왼쪽 가는 것을 dx,dy형태로 하고
현재 문제는 dfs(재귀) bfs(Queue)를 사용
3273번
처음에는 문제의 방향성은 잘 잡았는데 포인터 2개를 사용하는 것이 더 코드가 간단하고 문제 시간복잡도가 적게 나오긴함
13305번
생각보다는 쉬웠다고 생각하였지만 타입 오류로 인해 100점은 못 받은 문제 58점을 받은 이유로는 도시와 거리 값이 int 타입이아닌 long타입이였고 값의 범위를 확인하는 것이 중요
1735번
문젠는 크게 어렵진 않았지만 수학적으로 생각할 부분이 있었음. 시간복잡도를 어떻게 줄여야하는지는 아직 미지수..
=> [DFS,BFS,Imp,Greedy] 7주차

Goraniiii/Divide and Conquer/BOJ_1802.cpp, Goraniiii/Greedy/BOJ_1459.cpp, Goraniiii/Implementation/BOJ_14891.cpp
**BOJ 1802 : 종이 접기**
문제 규칙에 따라 보면 가운데 인덱스를 기준으로 양쪽이 접혔을 때 접힌 방향이 서로 반대여야함을 알 수 있음
n번 접었을 때 2^n - 1 의 접힌 점이 생김
2^n - 1 = k 로 놓고 문제를 풀면, 1 ~ (k - 1) / 2 와 (k + 1) / 2 ~ k 까지가 (k + 1) / 2 를 기준으로 reverse 대칭임
최초 가운데를 기준으로 반대대칭임을 확인하면 한쪽만 조건을 확인하면 되므로 1 ~ (k - 1) / 2 를 다시 검사
처음에는 재귀함수를 고려하였으나, 한쪽만 검사하면 되는 부분에서 k > 1 인 범위에서 분할 수행
문제 분류를 재귀로 시작했으나, 분할정복으로 풀이
**BOJ 1459 : 걷기**
스터디 초반에 시도했다가 실패한 문제
다시 풀어보니 케이스 하나를 누락한 경우
문제 조건을 살펴보면 s < w 인 케이스에 대해서만 추가로 생각하면 어렵지 않게 풀 수 있음
그래프 탐색이나 최단경로로 풀이할 수도 있으나, 문제 조건이 까다롭지 않아 직접 수식 적용하여 풀이.
**BOJ 14891 : 톱니바퀴**
최근 파이썬 위주로 사용했더니 c++ 기본 문법 이외에 클래스 등 문법이 기억나지 않아, 클래스 구조로 문제 풀이 진행
각 톱니바퀴를 wheel로 하여 데이터 저장과 회전 함수를 구현함. left, right 톱니 get method 역시 구현
문제 조건이 헷갈리게 제시되었으나, 파악 후 구현은 어렵지 않은 문제였음.
.emplace_back() 을 처음 알게되어 사용해보았다. 메모리 관리에서 단점이 있다고함.
c++ 객체지향 및 메모리 관리를 다시 …
=> [Greedy, Imp, Divide] 7주차

hyeyeonismm/implement/BOJ_1193.py, hyeyeonismm/sort/BOJ_10814.py, hyeyeonismm/sort/BOJ_1181.py
**1181**
dict를 선언해서, 문자열의 길이를 key로 설정해서 value로 값을 받았다. 값이 존재하는 경우에는 value에 들어오지 않도록 했고, 이를 sorted를 통해 key값을 기준으로 먼저 정렬했다. 이후, value를 기준으로 정렬했다.
**1193**
대각선의 수에 따라 규칙을 적용하고, 주어진 수가 몇 번째 라인에 속해있는지를 
while n > line:
n -= line
line += 1
이 while문을 통해 구현하면 더 쉬웠음
=> [Implement, Sort] 8주차

SeungJi20/Arithmetic/BOJ_10430.py, SeungJi20/Implementation/BOJ_10809.py, SeungJi20/Implementation/BOJ_11654.py
10430 : 나머지
10809 : 알파벳 찾기
find() 함수 : 첫 번째 등장 인덱스 반환, 없으면 -1
구조가 헷갈렸다. 소문자를 리스트에 range로 저장해두는게 핵심!
11654 : 아스키 코드
문자 -> 아스키 코드 : ord() 함수
아스키 코드 -> 문자 : chr() 함수
=> [Arithmetic, Implementation] 8주차

naarang/README.md, naarang/ShortestPath/BOJ_11403.js, naarang/ShortestPath/BOJ_11657.js, naarang/ShortestPath/BOJ_1753.js
최단 거리 알고리즘 3개를 이용해 문제를 풀이해봤습니다
알고리즘 | 목적 | 음수 가중치 | 음수 사이클 | 시간 복잡도 | 문제 유형
-- | -- | -- | -- | -- | --
다익스트라 | 단일 출발 최단 경로 | ❌ 불가능 | ❌ 불가능 | O((V + E) log V) | 빠르고 효율적이지만 음수 가중치 X
플로이드-워셜 | 모든 정점 쌍 최단 경로 | ✅ 가능 | ❌ 불가능 | O(V³) | 모든 경로 탐색 가능하지만 느림
벨만-포드 | 단일 출발 최단 경로 | ✅ 가능 | ✅ 감지 가능 | O(VE) | 음수 가중치 및 사이클 탐지 가능하지만 느림
=> [Shortest Path] 9주차

SeungJi20/Dynamic Programming/BOJ_15990.py, SeungJi20/Dynamic Programming/BOJ_9095.py, SeungJi20/Implementation/BOJ_2753.py
[Implementation] 9주차
2753 : 윤년
and랑 or을 써서 조건문을 세우면 됐던 문제다. 
9095 : 1, 2, 3 더하기
이 문제는 규칙이 잘 안보였다.
이전에 구한 값을 다음에 활용할 수 있기 때문에 DP 문제다.
예) 4 = 1 + 3 -> 3 방법의 수와 같음
4= 2 + 2 -> 2 방법의 수와 같고, 4 = 3 + 1 은 1 방법의 수랑 같다.
15990 : 1, 2, 3 더하기 5
9095의 응용 버전인데 어려웠다.
수식을 세워서 해결할까 했으나.. 마지막에 사용한 숫자를 기준으로 DP 배열을 나누는 문제였다.
마지막 숫자가 1이면 이전 숫자가 2 또는 3 이면 됨
* 나머지를 통해 오버플로우 방지해야 함
=> [Implementation, DP] 9주차

Goraniiii/BFS/BOJ_14226.cpp, Goraniiii/Tree/BOJ_1991.cpp, Goraniiii/Tree/BOJ_2250.cpp
=> [Tree, BFS] 10주차

rlaalsghks8/src/search/Problem2512.java, rlaalsghks8/src/search/Problem4963.java, rlaalsghks8/src/sort/Problem18870.java
18870번
입력 받은 숫자들을 정렬 한 다음에 다시 HashMap을 사용하여 순위와 key값(입력 받은 숫자들)을 넣어서 출력.
2512번
이분탐색으로 안 했다가 틀린 문제 이분 탐색 사용하면 쉽게 됨 
이분 탐색에 시작은 left=0,right= max(가장 큰 값 혹은 마지막 index)로 많이 사용됨
4963번
입력값을 배열 형태로 입력을 받으면 일반적으로 dx,dy를 사용하여 1차원 배열에 반복문을 통해 상하좌우, 대각선까지 이동하여 탐색을 진행하는 것이 일반적이다.
이 문제는 대각선까지 이동을 해야해서 아래 코드와 같이
```java
static int dx[] = {0, 0, -1 ,1, -1, 1, -1, 1};  
static int dy[] = {-1, 1, 0, 0, 1, 1, -1, -1};
``` 
해서 배열을 탐색 dfs 를 사용, 재귀함수 사용이 일반적 bfs인 경우는 Queue 사용
=> [Search,Sort] 10주차

SeungJi20/Bruteforcing/BOJ_1075.py, SeungJi20/Bruteforcing/BOJ_10974.py, SeungJi20/Dynamic Programming/BOJ_16395.py
1075 : 나누기
숫자 N 마지막 두 자리 숫자 00으로 바꾸기 
`N2 = (N // 100) * 100`
10974 : 모든 순열
가능한 모든 경우를 나열해야 하므로 brute force 문제이다.
직접 함수를 생각하려니 어려웠는데,
내장 라이브러리 itertools.permutations() 를 이용하면 더 쉽게 구할 수 있는 문제였다..
`*perm` : 튜플의 각 요소
16395 : 파스칼의 삼각형
먼저 모든 값을 0으로 초기화 해야한다 !!
그리고 출력하기 전에 미리 삼각형을 다 만들어야 한다
입력 값이 1부터 시작하므로, 인덱스도 1부터 시작하는 것으로 맞춤!
`dp = [[0] * (n + 1) for _ in range(n + 1)]`
=> [Bruteforcing, DP] 10주차

naarang/Implementation/BOJ_[1차]캐시.js, naarang/Implementation/PGS_[1차]뉴스클러스터링.js, naarang/Implementation/PGS_[1차]셔틀버스.js, naarang/README.md
=> [Implementation] 10주차

Goraniiii/BFS/BOJ_1012.cpp, Goraniiii/BFS/BOJ_1697.cpp, Goraniiii/BFS/BOJ_5014.cpp
숨바꼭질과 스타트링크 문제의 경우 기본적인 BFS 탐색으로 최단시간을 찾아내면 되는 문제였다.
유기농배추 문제는 BFS와 DFS가 관계 없는 문제였는데, 인접 배추들을 탐색하는 연결요소 문제였다.
=> [BFS] 11주차

chungchae/DFS_BFS/BOJ_18352.cpp, chungchae/DP/BOJ_11726.cpp, chungchae/DP/BOJ_1912.cpp
그래프를 2차원 배열로 입력받고, BFS로 탐색했다.
```
while (!Q.empty()) {
front = Q.front();
visited[front] = true;
for (int i : arr[front]) {
if (!visited[i])
{
visited[i] = true;
Q.push(i);
distance[i] = distance[front] + 1;
}
}
Q.pop();
}
```
=> [DP, BFS] 11주차

SeungJi20/Mathematics/BOJ_1292.py, SeungJi20/Mathematics/BOJ_1978.py, SeungJi20/Mathematics/BOJ_2581.py
1292 : 쉽게 푸는 문제
1부터 B까지의 수열을 만들고, A~B 구간의 합을 구하는 방식
이중 for문을 사용하여 수열을 생성한 후 슬라이싱으로 범위 합을 계산한다.
이중 for문에 좀 더 익숙해져야 할 것 같다.
1978 : 소수 찾기
루트x 까지만 검사하면 되는 더 효율적인 방법도 있었다.
`for i in range(2, int(x**0.5) + 1):`
2581 : 소수
1978번과 유사한데, 소수를 저장해야 한다는 점에서 다르다.
이 문제는 루트x 까지만 검사했다.
=> [Mathematics] 11주차

Goraniiii/Greedy/BOJ_10610.cpp, Goraniiii/Greedy/BOJ_11047.cpp, Goraniiii/Greedy/BOJ_11399.cpp
그리디 문제를 거의 공부하지 않은 것 같아 풀기 시작했다.
다른 유형에 비해서 사고력이 크게 떨어진다
기초 레벨로 3문제 풀이
=> [Greedy] 12주차

SeungJi20/String/BOJ_1157.py, SeungJi20/String/BOJ_1251.py, SeungJi20/String/BOJ_2675.py
1157 : 단어 공부
마지막에 문자를 출력하기 위해 인덱스 값에 ord('A')를 더해줘야 함
`print(chr(count.index(max_count) + ord('A')))`
1251 : 단어 나누기
이중 for문
1. 두 위치를 기준으로 단어를 세 부분으로 나눔
2. 각 부분을 뒤집고 이어 붙여, 새로운 단어를 만듦
3. 모든 조합을 리스트에 저장한 후, 사전순 정렬해서 가장 앞에 오는 단어를 출력
2675 : 문자열 반복
input에서 받은거 int로 형변환 꼭 해야 함
문자열 반복 두가지 방법
1. `result += char * r` (현재 방식)
2. `''.join(char * r for char in s)` (join하는 방식도 있음)
=> [String] 12주차

chungchae/DFS_BFS/BOJ_1325.cpp, chungchae/DP/BOJ_2579.cpp, chungchae/DP/BOJ_9095.cpp
실버 난이도 문제들을 풀었다.
규칙 찾는 DP문제보다 이런 문제가 더 까다롭게 느껴진다..
주어진 조건을 보고 점화식을 어떻게 작성해야 하는지 파악해야 한다.
```
DP[1] = arr[1]; DP[2] = DP[1] + arr[2];
DP[3] = max(arr[1] + arr[3], arr[2] + arr[3]);
for (int i = 4; i <= N; i++) {
DP[i] = max(DP[i - 2], DP[i - 3] + arr[i - 1]) + arr[i];
```
=> [DP, BFS] 12주차

JungYujin/Hash/듣보잡1764.java, JungYujin/Hash/영단어암기는괴로워20920.java, JungYujin/String/접미사배열11656.java
1764 : 듣보잡
Set에 먼저 듣도 못한 사람을 넣고,, 보도 못한 사람을 입력 받으며 만약 듣도 못한 Set에 있는 사람이면 List에 저장한다.
그리고 List를 Sorting 하고 출력
20920 : 영단어 암기는 괴로워
HashMap에 단어와 빈도수를 Key, Value로 저장한다. 단어를 정렬할 때 compare함수를 Override해서 사용한다. 문제에 주어진 조건  순서대로 정렬 조건을 확인한다. 
11656 : 접미사 배열
문자열의 길이와 같은 크기의 배열을 생성하고, 반복문을 돌며 substring을 사용해 i~문자열 끝까지 인 String을 저장한다. 
이를 List로 변환 후 Sorting해서 출력한다.
=> String, Hash [12주차]

naarang/DynamicProgramming/PGS_N으로표현.js, naarang/DynamicProgramming/PGS_등굣길.js, naarang/DynamicProgramming/PGS_정수삼각형.js, naarang/GraphTraversal/PGS_네트워크.js, naarang/README.md
=> [DP/Graph Traversal] 12주차

SeungJi20/String/BOJ_1152.py, SeungJi20/String/BOJ_1316.py, SeungJi20/String/BOJ_2744.py
1152 : 단어의 개수
count() : 리스트의 특정 값이 몇 번 등장했는지
len() : 리스트의 전체 길이
1316 : 그룹 단어 체커
현재 문자와 다음 문자를 비교
만약에 같지 않을 경우, 이전에 등장했던 문자인지 확인
`elif word[j] in word[j+1:]:`
* pass : 넘어가기
2744 : 대소문자 바꾸기
isupper() 함수 : 대문자인지 확인
결과 문자열을 만들 때 +=로 이어붙임
=> [String] 13주차

JungYujin/Hash/차집합1822.java, JungYujin/Implementation/배열복원하기16967.java, JungYujin/Sorting/보물1026.java
1822 : 차집합
집합 A를 TreeSet에 저장하고, B를 입력 받으며 해당 요소가 tree에 있는지 확인하고 있으면 tree에서 삭제한다. 조건에서 요소를 증가하는 순서로 출력하라고 하였으므로 HashSet이 아닌 요소가 자동으로 정렬되는 TreeSet에 저장해야한다.
16967 : 배열 복원하기
배열이 겹쳐지지 않는 부분은 a[i][j]를 그대로 쓰고, 겹쳐지는 부분은 a[i][j] = b[i][j]-a[i-x][j-y]의 규칙이 있다는 점을 이용하여 채운다.
1026 : 보물
수를 가장 작게 만들기 위해서는 A의 가장 작은 수와 B의 가장 큰 수를 곱하도록 하면 된다. 
따라서 listA는 sort, listB는 reverse하여 곱한다.
=> [Sorting, Hash, Implementation] 13주차

hyeyeonismm/implement/PGS_1차비밀지도.py, hyeyeonismm/implement/PGS_개인정보수집유효기간.py, hyeyeonismm/sort/BOJ_3758.py
**3758**
파이썬 다중 조건 정렬: sorted(x, key=lambda x: (x[0], x[1], x[2])
**개인정보 수집 유효기간**
index()를 사용하면 중복된 데이터가 있는 경우에 유의해야 함
=> [Implementation] 13주차

naarang/Backtracking/PGS_불량사용자.js, naarang/BinarySearch/PGS_징검다리건너기.js, naarang/README.md, naarang/TwoPointer/PGS_보석 쇼핑.js
투 포인터로 양쪽에서 줄여나가는 방식은 최소 길이를 보장하지 않음!
```
찾은 반례 :	["1", "1", "2", "2", "3", "3", "1", "2", "3"]
```
따라서 왼쪽 포인터를 이동시키면서 보석을 제거하고, 오른쪽 포인터를 이동시키면서 보석을 추가하여 모든 종류를 포함하는 최소 구간을 찾는 방식을 사용!
---
근데 stones 배열의 각 원소들의 값이 200000000 이하인 자연수이므로 단순 for문으로 하면 안된다!
가장 먼저 k개의 0개가 나오는 구간(k개의 값 중에서 최대값이 가장 작은 곳!)을 찾아서 해당 구간의 최대값을 구하기 -> 최대값 - 1이 정답!
슬라이딩 윈도우 이용하기 -> 라고 생각해도 숫자가 너무 커서 이진탐색이 필요했다..
돌의 값에 초점이 아니라 사람 인원수에 따라 이진탐색을 진행하기!
그리고 `Math.max(...stones)`로 했다가 시간초과! Math 메소드 사용도 주의하자
=> [Backtracking/BinarySearch/TwoPointer] 13주차

Goraniiii/Graph/BOJ_16947.cpp, Goraniiii/Greedy/BOJ_1541.cpp, Goraniiii/Greedy/BOJ_1931.cpp
그리디 2문제 해결
잃어버린 괄호 문제는 생각보다 허무하게 풀렸다. 한번 뺄셈 기호가 나오면 뒤에 있는 모든 수는 뺄셈이 가능하기 때문에... 오히려 연산자와 숫자 분리가 더 오래걸렸다.
서울 지하철 2호선 문제는 그래프에서 사이클을 찾고, 각 노드에서 사이클까지의 거리를 구하는 문제이다. 사이클 탐색은 해결했으나, 거리 구하는 부분을 해결하지 못했다.
=> [Greedy, Graph] 13주차

rlaalsghks8/src/dp/Problem11727.java, rlaalsghks8/src/implement/Problem11659.java, rlaalsghks8/src/implement/Problem3758.java
11658번
해당 문제는 N, M이 100,000 이하이다.
일반적으로 입력 받은 값을 배열(arr)에 넣어서 구간 별 합을 넣어서 출력하면 시간초과가 발생한다.
따라서 다른 방식으로 접근을 해야함
Hint로는 누적합으로 누적합의 배열을 만들어서
sum[M] → 에 sum[1]은  arr[1] sum[2] = arr[1] + arr[2] 이런 식으로 저장을 한다. 따라서 구간 별 합을 구하기 위해서는 
만약 2~4의 경우는 arr[4] - arr[1]만 해주면 간단하게 구간의 합이 나온다.
11727번
dp[1] = 1
dp[2] = 3
dp[3] = 5
dp[4] = 11
dp[5] = 21
dp[i] = (dp[i-1] + (dp[i-2]*2));
3758번
여기서 문제 해결하는 것에 가장 중요한 부분은 제출 시간이 더 빠른 팀의 순위를 판단하는 것이다.
여기서 입력 형태를 보면 나중에 넣은 팀 ID 값이 나의 팀인 경우 Rank ++ 증가시킨다. 
여기서 배운 점이 Stack에서 stack.search()를 할 경우 가장 늦게 들어간 값의 index를 출력한다.
값을 빼기 보다는 search를 통해 index값을 가지고 온다. 가지고 온 index값이 큰 경우는 가장 먼제 제출한 것이고 작은경우는 늦게 제출한 경우이다.
=> [Imp,DP] 14주차

chungchae/Data structure/BOJ_1620.cpp, chungchae/Math/BOJ_1072.cpp, chungchae/greedy/BOJ_1515.cpp, chungchae/slidingWindow/BOJ_11003.cpp, chungchae/stack/BOJ_10828.cpp
S3 ~ S4 난이도 문제들을 풀었다.
간단한 문제인데 알고리즘을 떠올리는 게 어려웠다. 문자열과 현재 수가 일치하면 계속 탐색하고, 다르면 현재 수를 1 증가시켜 다시 비교한다. 이 과정에서 끝까지 탐색하면 현재 수를 출력한다.
```
while (i < target.size()) {
string cur = to_string(num);
for (char c : cur) {
if (c == target[i])
{
i++;
if (i == target.size())
break;
}
}
num++;
}
```
=> [Data structure, Math] 14주차

SeungJi20/Implementation/BOJ_10773.py, SeungJi20/Implementation/BOJ_11866.py, SeungJi20/Implementation/BOJ_2161.py
2161 : 카드1
리스트로 풀면 deque 없이 풀 수 있지만,
리스트로 풀지 않고 collections.deque 를 사용하면 편하다.
popleft() : 맨 앞 제거
`print(*result)` : result 안에 있는 요소들을 하나씩 출력
10773 : 제로
별도의 자료구조 없이 list에 append()와 pop()을 이용하면 스택처럼 사용 가능
11866 : 요세푸스 문제 0
원형 순환 : (현재 위치 + k - 1) % 남은 사람 수
=> [Implementation] 14주차

SeungJi20/String/BOJ_11655.py, SeungJi20/String/BOJ_11721.py, SeungJi20/String/BOJ_8958.py
8958 : OX퀴즈
X가 나왔을 때, 기존에 있던 O개수와 점수를 따로 저장해야 하므로
변수가 두 개 필요하다! 
11655 : ROT13
z를 넘어가는 상황 고려를 못했다
소문자랑 대문자는 구분해서 풀어야 함
11721 : 열 개씩 끊어 출력하기
* 출력할 때 문자열 변환해서 출력하는거 잊지말기
`print("".join(string))`
반복문 끝나고 남은 문자도 출력해줘야 함
슬라이싱으로 간단한 방법도 있었다
=> [String] 15주차

rlaalsghks8/src/implement/PG_1_SecretMap.java, rlaalsghks8/src/implement/PG_CollectInfo.java, rlaalsghks8/src/implement/PG_GetManyGift.java
개인정보 수집 유효기간
이 문제는 생각보다 간단함. 여기서 발생하는 시작일이 1일 경우 만료 기한은 28로 가며 Month를 -1 감소해줘야한다.
또 Month가 12 이상이면 Year에도 1을 추가해야하며 24이상인 경우 2를 추가해주는 생각을 해야한다. 그래야지 다른 테스트케이스를 통과하는것 같다.
[1차]비밀지도
Math.pow() → 반환 타입은 Double이다.
System.out.println(num & (1 << 3)); // 1001 & 1000 = 1000 (8)
System.out.println(num & (1 << 2)); // 1001 & 0100 = 0000 (0)
System.out.println(num & (1 << 0)); // 1001 & 0001 = 0001 (1)
int num1 = 15;
int num2 = 20;
int num3 = num1 & num2;
직접 비트연산으로 계산하고 십진수로 계산 출력
num3 = 4 
00001111 & 00010100 = 00000100
<< i (shift연산) *(2*i)
>> i (shift연산) /(2*i)
가장 많이 받은 선물 
음.. 데이터를 어떤 곳에 활용하여 빼낼지 중요한 문제
가장 key Point는 friends의 index를 어떻게 설정할지 
HashMap이 적합 HashMap<String,Integer> 여기서 String은 사람 이름, Integer을 index를 저장하여 key값(사람이름)으로 Index를 꺼내고 기본 입출력 예 #1을 기반으로 문제를 해결해야한다. 
입출력 예를 보면 비교하는 방법과 선물지수를 …
=> Programmers [IMP] 15주차

naarang/GraphTraversal/BOJ_14502.py, naarang/GraphTraversal/BOJ_16234.py, naarang/GraphTraversal/BOJ_18405.py, naarang/GraphTraversal/PGS_괄호변환.py, naarang/Greedy/PGS_무지의먹방라이브.py, naarang/Implementation/BOJ_3190.py, naarang/README.md
이번주는 파이썬으로 푸는 것에 익숙해지는 연습을 했습니다!
=> [GraphTraversal/Implementation] 15주차

rlaalsghks8/src/dp/Problem1149.java, rlaalsghks8/src/implement/Problem21921.java, rlaalsghks8/src/search/Problem1987.java
1987번
백트래킹은 DFS(재귀)를 고집하여 푸는 것 같음. DFS문제에서도 상하좌우,(대각선까지)이동하는 문제에도 똑같이 적용해서 푸는 것 같음, 그리고 배열의 입력값이 문자인 경우는 무조건 ‘A’,’a’,특정 기준이 되는 ASCII코드값의 정수변환형을 빼준다.
```java
public static void dfs(int x, int y, int count){
visit[arr[x][y]] = true;
ans = Math.max(ans,count);
for(int i=0; i<4; i++){
int cx = x + dx[i];
int cy = y + dy[i];
if(cx>=0 && cy>=0 && cx<R && cy<C){
if(!visit[arr[cx][cy]]){
dfs(cx,cy,count+1);
}
}
}
visit[arr[x][y]] = false;
}
```
1149번
문제 이해가 어렵고 DP인것은 파악했지만 점화식 세우기가 어려움
21921번
문제 이해와 이전에 풀었던 구간합과 유사한문제 조금더 응용했다면
풀 수 있었음 다익스트라로 하면 시간초과가 발생
=> [DP,Search,Imp] 16주차

SeungJi20/Sorting/BOJ_10814.py, SeungJi20/Sorting/BOJ_25305.py, SeungJi20/Sorting/BOJ_2587.py
2587 : 대표값2
input 한줄입력
sorted 바로 사용
10814 : 나이순 정렬
나이가 같을 경우도 고려해야 함
나이가 같으면 입력 순서대로 출력됨
(sorted에서 lambda 사용하여 정렬 기준을 설정)
25305 : 커트라인
`.sort(reverse=True)` 내림차순
=> [Sorting] 16주차

chungchae/stack_queue/BOJ_9935.cpp, chungchae/stack_queue/PGS_같은숫자는싫어.cpp, chungchae/stack_queue/PGS_기능개발.cpp, chungchae/stack_queue/PGS_다리를건너는트럭.cpp, chungchae/stack_queue/PGS_더맵게.cpp, chungchae/stack_queue/PGS_주식가격.cpp, chungchae/stack_queue/PGS_프로세스.cpp
스택, 큐 문제를 풀었다.
앞 요소와 비교해 다른 경우에만 push_back 한다.
건너는 트럭이 아니라 지나는 트럭이었다.....
건너는 중인 트럭은 pair<int, int> 벡터 Q1(무게, 대기 시간), 대기 트럭은 int 큐 Q2 로 선언했다.
Q1의 front의 대기 시간이 0이면 pop 한다.
다음 트럭이 다리에 진입할 때, 전체 무게가 초과하지 않으면 진입시킨다.
매 반복마다 다리 위 트럭들의 대기 시간을 1씩 감소시킨다.
```
// 매 반복마다 1초씩 증가
answer++;
// 0. Q1의 front의 대기시간을 확인, 0이면 pop
if (!Q1.empty() && Q1[0].second == 0){
now_weight -= Q1[0].first;
Q1.erase(Q1.begin());
}
// 1. 건너는 트럭 + 다음 트럭이 무게를 초과하지 않는 경우
if( !Q2.empty() && now_weight + Q2.front() <= weight){
now_weight += Q2.front();
Q1.push_back({Q2.front(), bridge_length});
Q2.pop();
}
// 2. 건너는 트럭 + 다음 트럭이 무게를 초과하는 경우
else {
// 아무것도 안한다
}
// 매 반복마다, Q1의 요소들의 대기시간을 1씩 줄인다.
for (int i=0; i < Q1.size(); i++){
Q1[i].second--;
}
}
```
=> [Stack, Queue] 16주차

Goraniiii/Graph/BOJ_2468.cpp, Goraniiii/Heap/BOJ_11279.cpp, Goraniiii/Math/BOJ_1002.cpp
<b>BOJ 1002 : 터렛</b>
두 원의 중심과 반지름에 대해 교점조건을 구하는 문제.
<b>BOJ 2468 : 안전영역</b>
문제 조건이 조금 이해하기 어려웠으나 case 별로 그래프탐색을 진행하여 분리된 개별 영역의 수를 구하는 문제
<b>BOJ 11279 : 최대 힙</b>
힙 전혀 문제를 안 풀어본 것 같아서 풀어봄.
기본 배열로 직접 최대 힙을 구현했는데, 힙 최대 크기에 대해 참조범위를 잘못 생각해 오래 걸렸다. 혹은 예외처리를 했어야했는데 둘 다 생각하지 못해 오래 붙잡았다.
=> [Math, Graph, Heap] 17주차

SeungJi20/Bruteforcing/BOJ_1018.py, SeungJi20/Bruteforcing/BOJ_1436.py, SeungJi20/Bruteforcing/BOJ_2798.py
1018 : 체스판 다시 칠하기
어려운 문제였다..
1) 체스판을 두 가지 색 배열로 만듦
2) 8x8 부분을 자르고, 각 부분을 두 색 배열과 비교
3) 각 부분에 대해 최소 변경 횟수를 구하고, 그 중 가장 작은 값을 출력
1436 : 영화감독 숌
in 연산자 : 문자열 안에 어떤 부분 문자열이 있는지 볼 때 사용
숫자가 아니라 문자열로 만들어야 함
2798 : 블랙잭
3중 for문 사용
=> [Bruteforcing] 17주차

naarang/BinarySearch/BOJ_입국심사.py, naarang/GraphTraversal/PGS_게임맵최단거리.py, naarang/GraphTraversal/PGS_단어변환.py, naarang/README.md
=> [BinarySearch/GraphTraversal] 17주차

JungYujin/Implementation/상수2908.java, JungYujin/Implementation/숫자의개수2577.java, JungYujin/Implementation/평균1546.java, JungYujin/Search/그림1926_2.java, JungYujin/Search/순열사이클10451.java
=> [Sortin, Implementation] 18주차

chungchae/DFS_BFS/PGS_네트워크.cpp, chungchae/hash/PGS_베스트앨범.cpp, chungchae/hash/PGS_완주하지못한선수.cpp, chungchae/hash/PGS_의상.cpp, chungchae/hash/PGS_전화번호목록.cpp, chungchae/hash/PGS_폰켓몬.cpp
해시 문제들을 풀었다. map이나 set 자료를 사용하는 경우가 많다.
```
// 정렬되지 않는 맵, 중복 비허용
unordered_map<string, int> M;
// 두번째 값 (옷 종류)의 해시 value를 1 증가
for (int i = 0; i < clothes.size(); i++) {
M[clothes[i][1]]++;
}
// M의 key, value에 대해서
for (const auto& [key, value] : M) {
// 입지 않는 경우까지, +1
answer *= (value + 1);
}
```
정렬 후 위치를 찾아, 0이면 접두어로 판단한다.
```
sort(phone_book.begin(), phone_book.end());
for (int i = 0; i < phone_book.size() - 1; i++) {
// find의 반환값이 0이면, 접두어
if (phone_book[i + 1].find(phone_book[i]) == 0)
return false;
}
```
=> [Hash] 18주차

SeungJi20/Mathematics/BOJ_1094.py, SeungJi20/Mathematics/BOJ_1676.py, SeungJi20/Mathematics/BOJ_2747.py
1094 : 막대기
제일 긴 막대기부터 해서 반씩 자르면 됨
아니면 미리 가능한 길이를 리스트에 담아도 될 거 같다.
1676 : 팩토리얼 0의 개수
팩토리얼 계산 결과에서 0의 개수는 5의 개수가 결정!
짝수(2)는 충분히 많기 때문
2747 : 피보나치 수
=> [Mathematics] 18주차

SeungJi20/BFS/BOJ_10026.py, SeungJi20/BFS/BOJ_1260.py, SeungJi20/BFS/BOJ_2606.py
1260 : DFS와 BFS
DFS는 재귀로, BFS는 반복문으로 구현
결과는 *을 사용해 리스트의 요소를 한 줄로 출력, 
줄바꿈도 자동으로 됨
2606 : 바이러스
그래프 입력
```
graph = [[] for _ in range(n+1)]
for _ in range(m): 
a, b =map(int, input().split())
graph[a].append(b)
graph[b].append(a)
```
함수 매개변수는 자료형 지정 안해도 됨
`def bfs(start):`
10026 : 적록색약
- visited 배열로 방문 여부를 확인하고
- 상하좌우 방향 벡터를 설정하여 이동하면서
- 현재의 색과 같은 색인지 계속 확인.
=> [BFS] 19주차

rlaalsghks8/src/dp/Problem2240.java, rlaalsghks8/src/dp/Problem2302.java, rlaalsghks8/src/greedy/Problem15903.java
2240번
DP는 항상 어렵다. 해당 문제는 보기엔 쉽게 구현할 수 있을 것 같지만
예제만 봐도 경우가 다양하게 나온다. 따라서 DP라는 것을 알 수 있는데 
DP 2차원 배열로 두고 0인덱스는 1번나무 1인덱스는 2번나무로 설정하여 계산을 한다. DP에 당연히 사과의 갯수를 넣어야하며 가만히 있는 경우와 이동을 했을 때의 경우를 또 나눠서 dp를 적용해야한다.
다시 풀어보면 좋을 것 같은 문제 각 경우에 따라 dp를 다르게 기록하는 문제이다.
2303번
해당 문제는 생각보다 간단하게 구할 수 있는 문제이다. 고정된 좌석으로 dp안의 있는 값을 구해주면 되고 flag(vip)값을 세워 구간 범위의 dp[구간 범위]의 값을 answer에 곱해주면 되는 것이다. 
15903번
이번에도 Type이 중요하다. int가 아닌 Long으로 해야함. 생각보다 쉬움 타입만 주의하면서 풀자
=> [DP,Greedy] 19주차

chungchae/DFS_BFS/PGS_소수찾기.cpp, chungchae/DFS_BFS/PGS_전력망을둘로나누기.cpp, chungchae/DFS_BFS/PGS_타겟넘버.cpp, chungchae/DFS_BFS/PGS_피로도.cpp
DFS, BFS 문제를 풀었다.
던전 배열, 방문 여부 배열, 깊이, 현재 피로도, 정답 배열을 인수로 갖는 DFS 배열을 사용한다.
```
void DFS(vector<vector<int>> dungeons, vector<bool>& visited, int depth, int now, int& answer) {
answer = max(answer, depth);
// depth가 최대인 경우 종료
if (depth == dungeons.size())
return;
for (int i = 0; i < dungeons.size(); i++) {
if (!visited[i] && dungeons[i][0] <= now) {
visited[i] = true;
DFS(dungeons, visited, depth + 1, now - dungeons[i][1], answer);
visited[i] = false;
}
}
}
```
=> [DFS, BFS] 19주차

Goraniiii/Heap/PGS_42626.cpp, Goraniiii/Heap/PGS_42627.cpp, Goraniiii/Heap/PGS_42628.cpp
Heap 문제를 3문제 풀었다. 우선순위큐나 멀티셋을 이용하였다.
=> [Heap] 19주차

Goraniiii/Greedy/PGS_42860.cpp, Goraniiii/Greedy/PGS_42862.cpp, Goraniiii/Greedy/PGS_42883.cpp
=> [Greedy] 20주차

JungYujin/DP/점프점프11060.java, JungYujin/DP/피보나치함수1003.java, JungYujin/Implementation/분수찾기1193.java
=> [DP, Implemantation] 20주차

hyeyeonismm/graph/BOJ_10451.py, hyeyeonismm/graph/BOJ_4803.py
=> [Graph] 20주차

SeungJi20/String/BOJ_11656.py, SeungJi20/String/BOJ_25206.py, SeungJi20/String/BOJ_4470.py
4470 : 줄번호
`sentence += input()`
문자열을 문자 단위로 나눠서 리스트에 넣는 것임
append : 한 문장씩 저장
11656 : 접미사 배열
리스트 정렬 : sorted()
한글자씩 추가하는 게 필요하다고 생각해서 new라는 변수를 만들었는데,
이미 문자열 S를 받아왔으므로 바로 S[i:]를 사용하면 됨
25206 : 너의 평점은
성적을 평점으로 변환 : 딕셔너리 사용
성적이 전부 P인 경우, 예외처리해서 따로 출력
=> [String] 20주차

SeungJi20/DataStructures/BOJ_17608.java, SeungJi20/DataStructures/BOJ_2605.java, SeungJi20/DataStructures/BOJ_9935.java, SeungJi20/String/BOJ_1152.java
1152 : 단어의 개수
for문으로 돌려서 했는데.. StringTokenizer를 사용하면 훨씬 간결하게 풀 수 있었다.
StringTokenizer는 연속된 공백을 한개로 보기 때문에 
공백의 개수만 중요한 이 문제에서 이를 사용하면 적절하다.
출력은 한줄이므로 그냥 println으로 했다.
2605 : 줄서기
ArrayList가 훨씬 편함(동적)
`line.add(i - move, i + 1);`
17608 : 막대기
`max = len[i];`
맨 끝보다 길어야 함 + 다른 더 긴 막대기 뒤에 숨겨질 수도 있으므로
최댓값을 계속 바꿔야 함
그리고 뒤에서부터 비교해야 함 ( 방향성이 중요..)
'or (int i = N-2; i >= 0; i--)'
=> [String, Data Structures] 21주차

chungchae/DFS_BFS/PGS_피로도.cpp, chungchae/DP/BOJ_1932.cpp, chungchae/DP/PGS_멀리뛰기.cpp, chungchae/Implementation/PGS_최솟값만들기.cpp, chungchae/greedy/BOJ_1049.cpp, chungchae/greedy/PGS_귤고르기.cpp, chungchae/greedy/PGS_점프와순간이동.cpp, chungchae/greedy/PGS_큰수만들기.cpp
greedy, DP 문제를 풀었다.
```
while (n != 1) {
// 2로 나눠지면 순간이동,
if (n % 2 == 0) {
n /= 2;
}
// 아니라면 한 칸 이동 (건전지 사용)
else {
ans++;
n -= 1;
}
```
자식 노드 두 개 중 큰 값을 골라 더하기를 반복한다. root 노드까지 진행한 뒤 해당 값을 출력한다.
```
//아래 두 값 중, 큰 값을 더하기를 반복
for (int i = N - 1; i > 0; i--) {
for (int j = 0; j < i; j++) {
arr[i - 1][j] += max(arr[i][j], arr[i][j + 1]);
}
}
```
=> [greedy, DP] 20주차

hyeyeonismm/graph/BOJ_16953.py, hyeyeonismm/graph/BOJ_5567.py
=> [BFS] 22주차

chungchae/brute_force/BOJ_14888.cpp, chungchae/brute_force/PGS_모음사전.cpp, chungchae/brute_force/PGS_모의고사.cpp, chungchae/brute_force/PGS_최소직사각형.cpp
brute force 문제들을 풀었다.
그대로 넣는 경우와 돌려서 넣는 경우를 모두 시도해본다.
```
for (int i = 0; i < sizes.size(); i++) {
int a, b;
// 그대로 넣는 경우
a = abs(x_max - sizes[i][0]) + abs(y_max - sizes[i][1]);
// 돌려서 넣는 경우
b = abs(x_max - sizes[i][1]) + abs(y_max - sizes[i][0]);
if (a < b) {
x_max = max(x_max, sizes[i][0]);
y_max = max(y_max, sizes[i][1]);
}
else {
x_max = max(x_max, sizes[i][1]);
y_max = max(y_max, sizes[i][0]);
}
}
```
=> [brute force] 21주차

SeungJi20/Implementation/BOJ_1157.java, SeungJi20/Implementation/BOJ_2562.java, SeungJi20/Implementation/BOJ_2566.java, SeungJi20/Mathematics/BOJ_2292.java, SeungJi20/Sorting/BOJ_2675.java, SeungJi20/Sorting/BOJ_2750.java
1157 : 단어 공부
알파벳 빈도수 저장 => 알파벳 빈도수 배열 만들기
문자 횟수 세기 : `alphabet[c - 'A']++;`
마지막 출력에서 대문자로 출력해야 하므로 +65를 해야 함
`(char)(i + 'A');`
2292 : 벌집
수학적 규칙으로 찾았는데 
```
while (N > range) {
range += 6 * count; // 각 층마다 6의 배수만큼 방이 늘어남
count++;
}
```
이러한 방법이 있었다.
2562 : 최댓값
변수 범위가 항상 헷갈린다..
for문에서 i를 출력하기 위해서 `int index = 0`을 반복문 밖에 선언
2566 : 최댓값
`int max = Integer.MIN_VALUE;` 로 해야함
만약 int max = arr[0][0]으로 하게 되는경우,
입력에 음수가 있을 경우 최댓값 비교가 제대로 안됨 주의. 
한줄 통째로 입력 받는 법
```
for(int i=0; i<9; i++){
String[] input = br.readLine().split(" ");
for(int j=0; j<9; j++){
arr[i][j] = Integer.parseInt(input[j]);
}
```
2675 : 문자열 반복
S.length()만큼 돌면서 문자 하나씩 꺼냄 -> `S.charAt(j)`
2750 : 수 정렬하기
버블정렬 O(N²)
=> [Mathematics, String, Implementation] 23주차, 24주차

naarang/README.md, naarang/TreeDP/BOJ_15681.js, naarang/TreeDP/BOJ_1949.js, naarang/TreeDP/BOJ_2213.js
1 ≤ Q ≤ 10^5 이므로 각 노드의 서브쿼리의 개수를 미리 저장해야 함! (dp)
```
DFS의 경우 서브쿼리의 개수를 구해야하기 때문에 반복문보다 재귀가 훨씬 더 간편함
후처리(post-order)가 자연스럽게 구현됨
→ 재귀는 함수 호출이 끝난 후(=자식들을 모두 처리한 후) 부모로 돌아오기 때문에!
```
---
dp로 선택함 or 안 함을 계산
dp[node][0]: node가 우수 마을이 아닌 경우의 최대 주민 수
dp[node][1]: node가 우수 마을인 경우의 최대 주민 수
무방향그래프이므로 임의로 루트를 정하는 것이 편하다! (트리는 사이클이 없는 연결 그래프이기 때문에)
-> 트리에서 각 노드를 루트로 하는 서브트리에 대해 최적해를 계산
=> [Tree DP] 23주차

chungchae/2Pointer/BOJ_30804.cpp, chungchae/DP/BOJ_1904.cpp, chungchae/Implementation/BOJ_1074.cpp, chungchae/Math/BOJ_18110.cpp, chungchae/greedy/BOJ_1541.cpp, chungchae/sort/BOJ_10814.cpp, chungchae/sort/BOJ_11399.cpp, chungchae/sort/BOJ_18870.cpp, chungchae/stack_queue/BOJ_1966.cpp
DP로 풀이했다.
```
DP[1] = 1; DP[2] = 2;
for (int i = 3; i <= N; i++) {
DP[i] = (DP[i - 1] + DP[i - 2])% 15746;
}
cout << DP[N];
```
구역을 축소해가며, pow로 더해줄 수를 구했다.
```
// 정사각형 구역을 축소해가며 구현
for (int i = N - 1; i >= 0; i--) {
// 1. 행 처리
if (x > pow(2, i)) {
ans += pow(2, i) * pow(2, i) * 2;
x -= pow(2, i);
}
// 2. 열 처리
if (y > pow(2, i)) {
ans += pow(2, i) * pow(2, i);
y -= pow(2, i);
}
}
```
=> [Sort, DP]

chungchae/DFS_BFS/BOJ_10026.cpp, chungchae/DFS_BFS/BOJ_15650.cpp, chungchae/DFS_BFS/BOJ_15651.cpp, chungchae/Data structure/BOJ_11279.cpp, chungchae/Implementation/BOJ_18111.cpp, chungchae/Implementation/BOJ_2630.cpp, chungchae/binary_search/BOJ_2805.cpp
현재 좌표랑 색종이 사이즈 입력받아 분할 탐색하기
```
void colorCheck(int x, int y, int size) {
// x ~ x+size, y ~ y+size 까지 탐색
// B, W 중 하나의 색만 있는지 확인
int now_B = 0; int now_W = 0;
for (int i = x; i < x + size; i++) {
for (int j = y; j < y + size; j++) {
if (arr[i][j] == 0) now_W++;
else now_B++;
}
}
// 하나의 색만 있다면, B, W에 +1
if (now_B == 0)W++;
else if (now_W == 0)B++;
else {
// 색이 섞여 있다면, 4분할 재귀
colorCheck(x, y, size / 2);
colorCheck(x, y + size / 2, size / 2);
colorCheck(x + size / 2, y, size / 2);
colorCheck(x + size / 2, y + size / 2, size / 2);
}
}
```
높이랑 시간 우선순위거 까다로웠다. 현재 최대/최소값을 저장하는 변수로 판단하도록 구현했다.
=> [Implementation]
